/* Content for Перший Крок. Rows are compact tuples:
   [uk, translit, en, es, pt, section, exampleUk?, exampleEn?, exampleEs?, examplePt?] */
(function () {
  const SECTIONS = [
    { id: '01', uk: 'Звання', en: 'Ranks & forms of address', es: 'Rangos y tratamientos', pt: 'Patentes e formas de tratamento' },
    { id: '02', uk: 'Команди', en: 'Commands & drill language', es: 'Órdenes y voces de mando', pt: 'Comandos e vozes de comando' },
    { id: '03', uk: 'Медицина', en: 'Medical & casualty terms', es: 'Términos médicos y de bajas', pt: 'Termos médicos e de baixas' },
    { id: '04', uk: 'Спорядження', en: 'Gear & equipment', es: 'Equipo y material', pt: 'Equipamento e material' },
    { id: '05', uk: 'Напрямки', en: 'Directions & distance', es: 'Direcciones y distancias', pt: 'Direções e distâncias' },
    { id: '06', uk: 'Зв’язок і документи', en: 'Radio, reporting & paperwork', es: 'Radio, informes y documentación', pt: 'Rádio, relatórios e documentação' },
    { id: '07', uk: 'Побут', en: 'Daily life in a unit', es: 'Vida diaria en la unidad', pt: 'Dia a dia na unidade' },
    { id: '08', uk: 'Числа й час', en: 'Numbers & time', es: 'Números y hora', pt: 'Números e horas' },
  ];

  const ROWS = [
    ['солдат', 'soldat', 'soldier', 'soldado', 'soldado', '01'],
    ['сержант', 'serzhant', 'sergeant', 'sargento', 'sargento', '01'],
    ['старший сержант', 'starshyi serzhant', 'senior sergeant', 'sargento primero', 'primeiro-sargento', '01'],
    ['лейтенант', 'leitenant', 'lieutenant', 'teniente', 'tenente', '01'],
    ['капітан', 'kapitan', 'captain', 'capitán', 'capitão', '01'],
    ['командир', 'komandyr', 'commander', 'comandante', 'comandante', '01', 'Де командир?', 'Where is the commander?', '¿Dónde está el comandante?', 'Onde está o comandante?'],
    ['побратим', 'pobratym', 'brother-in-arms', 'hermano de armas', 'irmão de armas', '01'],
    ['рядовий', 'riadovyi', 'private', 'soldado raso', 'soldado raso', '01'],
    ['старший солдат', 'starshyi soldat', 'senior private / lance corporal', 'soldado de primera', 'soldado de primeira classe', '01'],
    ['молодший сержант', 'molodshyi serzhant', 'junior sergeant / corporal', 'cabo', 'cabo', '01'],
    ['головний сержант', 'holovnyi serzhant', 'master sergeant', 'sargento mayor', 'sargento-mor', '01'],
    ['старшина', 'starshyna', 'first sergeant / company sergeant', 'brigada', 'sargento-ajudante', '01'],
    ['старший лейтенант', 'starshyi leitenant', 'senior lieutenant', 'teniente primero', 'primeiro-tenente', '01'],
    ['майор', 'maior', 'major', 'mayor / comandante', 'major', '01'],
    ['полковник', 'polkovnyk', 'colonel', 'coronel', 'coronel', '01'],
    ['командир взводу', 'komandyr vzvodu', 'platoon commander', 'jefe de pelotón', 'comandante de pelotão', '01'],
    ['командир роти', 'komandyr roty', 'company commander', 'jefe de compañía', 'comandante de companhia', '01'],
    ['комбат', 'kombat', 'battalion commander (short form)', 'jefe de batallón', 'comandante de batalhão', '01'],
    ['відділення', 'viddilennia', 'squad / section', 'escuadra', 'esquadra', '01'],
    ['взвод', 'vzvod', 'platoon', 'pelotón', 'pelotão', '01'],
    ['рота', 'rota', 'company', 'compañía', 'companhia', '01'],
    ['Пане сержанте!', 'pane serzhante', 'Sergeant! (form of address)', '¡Sargento! (tratamiento)', 'Sargento! (tratamento)', '01', 'Пане сержанте, дозвольте звернутися.', 'Sergeant, permission to speak.', 'Sargento, permiso para hablar.', 'Sargento, permissão para falar.'],
    ['Так точно!', 'tak tochno', 'Yes, sir! / Affirmative!', '¡Sí, señor! / ¡Afirmativo!', 'Sim, senhor! / Afirmativo!', '01'],
    ['Ніяк ні!', 'niiak ni', 'No, sir! / Negative!', '¡No, señor! / ¡Negativo!', 'Não, senhor! / Negativo!', '01'],
    ['Слухаюсь!', 'slukhaius', 'Yes, sir! (will do)', '¡A la orden!', 'Às ordens!', '01'],
    ['Дозвольте звернутися.', 'dozvolte zvernutysia', 'Permission to speak.', 'Permiso para hablar.', 'Permissão para falar.', '01'],
    ['доброволець', 'dobrovolets', 'volunteer (military)', 'voluntario (militar)', 'voluntário (militar)', '01'],
    ['іноземець', 'inozemets', 'foreigner', 'extranjero', 'estrangeiro', '01'],
    ['перекладач', 'perekladach', 'interpreter', 'intérprete', 'intérprete', '01'],

    ['Стій!', 'stii', 'Halt! / Stop!', '¡Alto!', 'Alto!', '02'],
    ['Лягай!', 'liahai', 'Get down!', '¡Al suelo!', 'Ao chão!', '02'],
    ['Вперед!', 'vpered', 'Forward! / Move!', '¡Adelante!', 'Avançar!', '02'],
    ['В укриття!', 'v ukryttia', 'Take cover!', '¡A cubierto!', 'Abriguem-se!', '02', '«В укриття!»', '“Take cover!”', '«¡A cubierto!»', '«Abriguem-se!»'],
    ['Вогонь!', 'vohon', 'Fire!', '¡Fuego!', 'Fogo!', '02'],
    ['Не стріляти!', 'ne striliaty', "Don't shoot!", '¡No disparen!', 'Não atirem!', '02'],
    ['Зрозумів.', 'zrozumiv', 'Understood.', 'Entendido.', 'Entendido.', '02'],
    ['Повторіть.', 'povtorit', 'Say again.', 'Repita.', 'Repita.', '02'],
    ['Швидше!', 'shvydshe', 'Faster!', '¡Más rápido!', 'Mais rápido!', '02'],
    ['Тримай позицію!', 'trymai pozytsiiu', 'Hold the position!', '¡Mantén la posición!', 'Mantenha a posição!', '02'],
    ['Готовий?', 'hotovyi', 'Ready?', '¿Listo?', 'Pronto?', '02'],
    ['Струнко!', 'strunko', 'Attention!', '¡Firmes!', 'Sentido!', '02'],
    ['Вільно!', 'vilno', 'At ease!', '¡Descansen!', 'Descansar!', '02'],
    ['Шикуйсь!', 'shykuis', 'Fall in!', '¡En formación!', 'Formar!', '02'],
    ['Рівняйсь!', 'rivniais', 'Dress right! (align)', '¡Alinearse!', 'Alinhar!', '02'],
    ['Розійтись!', 'roziitys', 'Dismissed! / Fall out!', '¡Rompan filas!', 'Debandar!', '02'],
    ['До мене!', 'do mene', 'To me! / On me!', '¡A mí!', 'A mim!', '02'],
    ['За мною!', 'za mnoiu', 'Follow me!', '¡Síganme!', 'Sigam-me!', '02'],
    ['Бігом!', 'bihom', 'On the double! / Run!', '¡Corriendo!', 'Correndo!', '02'],
    ['Пішли!', 'pishly', "Let's go!", '¡Vamos!', 'Vamos!', '02'],
    ['Стоп!', 'stop', 'Stop!', '¡Stop!', 'Pare!', '02'],
    ['Назад!', 'nazad', 'Back! / Fall back!', '¡Atrás!', 'Para trás!', '02'],
    ['Відходимо!', 'vidkhodymo', "We're pulling back!", '¡Nos retiramos!', 'Estamos recuando!', '02'],
    ['Прикрий!', 'prykryi', 'Cover me!', '¡Cúbreme!', 'Me cubra!', '02'],
    ['Прикриваю!', 'prykryvaiu', 'Covering!', '¡Cubriendo!', 'Cobrindo!', '02'],
    ['Тривога!', 'tryvoha', 'Alarm! / Stand to!', '¡Alarma!', 'Alarme!', '02'],
    ['Повітря!', 'povitria', 'Air! (drone or aircraft threat)', '¡Aire! (amenaza aérea)', 'Ar! (ameaça aérea)', '02'],
    ['Дрон!', 'dron', 'Drone!', '¡Dron!', 'Drone!', '02'],
    ['Птах!', 'ptakh', 'Bird! (slang for drone)', '¡Pájaro! (jerga: dron)', 'Pássaro! (gíria: drone)', '02'],
    ['Контакт!', 'kontakt', 'Contact! (enemy)', '¡Contacto!', 'Contato!', '02'],
    ['Свої!', 'svoi', 'Friendlies! / Don’t shoot, own troops!', '¡Son nuestros!', 'São nossos!', '02'],
    ['Обережно!', 'oberezhno', 'Careful!', '¡Cuidado!', 'Cuidado!', '02'],
    ['Міни!', 'miny', 'Mines!', '¡Minas!', 'Minas!', '02'],
    ['Тихо!', 'tykho', 'Quiet!', '¡Silencio!', 'Silêncio!', '02'],
    ['Заряджай!', 'zariadzhai', 'Load!', '¡Carguen!', 'Carregar!', '02'],
    ['Розрядити зброю!', 'rozriadyty zbroiu', 'Unload weapon!', '¡Descarguen el arma!', 'Descarregar a arma!', '02'],
    ['Зброю до огляду!', 'zbroiu do ohliadu', 'Weapons for inspection!', '¡Armas para inspección!', 'Armas para inspeção!', '02'],
    ['На запобіжник!', 'na zapobizhnyk', 'Safety on!', '¡Seguro puesto!', 'Trava de segurança!', '02'],
    ['Ціль!', 'tsil', 'Target!', '¡Blanco!', 'Alvo!', '02'],
    ['Відбій!', 'vidbii', 'Stand down! / All clear! / Lights out!', '¡Retirada de alarma! / ¡Todo despejado!', 'Cessar! / Tudo limpo!', '02'],
    ['Так.', 'tak', 'Yes.', 'Sí.', 'Sim.', '02'],
    ['Ні.', 'ni', 'No.', 'No.', 'Não.', '02'],
    ['Не зрозумів.', 'ne zrozumiv', "I didn't understand.", 'No entendí.', 'Não entendi.', '02'],
    ['Повільніше, будь ласка.', 'povilnishe, bud laska', 'Slower, please.', 'Más despacio, por favor.', 'Mais devagar, por favor.', '02'],
    ['Покажи.', 'pokazhy', 'Show me.', 'Muéstrame.', 'Me mostre.', '02'],
    ['Чекай.', 'chekai', 'Wait.', 'Espera.', 'Espere.', '02'],
    ['Бачу.', 'bachu', 'I see it.', 'Lo veo.', 'Vejo.', '02'],
    ['Не бачу.', 'ne bachu', "I don't see it.", 'No lo veo.', 'Não vejo.', '02'],
    ['Осічка!', 'osichka', 'Misfire!', '¡Fallo de tiro!', 'Falha de tiro!', '02'],
    ['Заклинило!', 'zaklynylo', 'Jammed! / Stoppage!', '¡Encasquillada!', 'Travou!', '02'],
    ['Дивись.', 'dyvys', 'Watch. / Look.', 'Mira.', 'Olhe.', '02'],
    ['Повторюй за мною.', 'povtoriui za mnoiu', 'Repeat after me.', 'Repite conmigo.', 'Repita comigo.', '02'],
    ['Ще раз.', 'shche raz', 'Once more. / Again.', 'Otra vez.', 'De novo.', '02'],
    ['Правильно.', 'pravylno', 'Correct.', 'Correcto.', 'Certo.', '02'],
    ['Неправильно.', 'nepravylno', 'Wrong. / Incorrect.', 'Incorrecto.', 'Errado.', '02'],
    ['Молодець!', 'molodets', 'Well done!', '¡Bien hecho!', 'Muito bem!', '02'],

    ['поранений', 'poranenyi', 'casualty / wounded', 'herido', 'ferido', '03', 'Маємо пораненого!', 'We have a casualty!', '¡Tenemos un herido!', 'Temos um ferido!'],
    ['медик', 'medyk', 'medic', 'sanitario', 'socorrista', '03', 'Потрібен медик!', 'We need a medic!', '¡Necesitamos un sanitario!', 'Precisamos de um socorrista!'],
    ['джгут', 'dzhhut', 'tourniquet', 'torniquete', 'torniquete', '03', 'Наклади джгут!', 'Apply a tourniquet!', '¡Pon un torniquete!', 'Aplique um torniquete!'],
    ['допомога', 'dopomoha', 'help / aid', 'ayuda', 'ajuda', '03'],
    ['евакуація', 'evakuatsiia', 'evacuation', 'evacuación', 'evacuação', '03'],
    ['кровотеча', 'krovotecha', 'bleeding', 'hemorragia', 'hemorragia', '03'],
    ['ноші', 'noshi', 'stretcher', 'camilla', 'maca', '03'],
    ['нога', 'noha', 'leg', 'pierna', 'perna', '03'],
    ['рука', 'ruka', 'arm / hand', 'brazo', 'braço', '03'],
    ['дихає', 'dykhaie', 'breathing (he/she is)', 'respira', 'respira', '03'],
    ['Не дихає!', 'ne dykhaie', 'Not breathing!', '¡No respira!', 'Não respira!', '03'],
    ['турнікет', 'turniket', 'tourniquet (also very common)', 'torniquete', 'torniquete', '03'],
    ['аптечка', 'aptechka', 'IFAK / first-aid kit', 'botiquín', 'kit de primeiros socorros', '03', 'Де твоя аптечка?', 'Where is your IFAK?', '¿Dónde está tu botiquín?', 'Onde está seu kit?'],
    ['триста', 'trysta', '“300” — wounded (radio code)', '«300» — herido (código)', '«300» — ferido (código)', '03', 'У нас триста!', 'We have a wounded man!', '¡Tenemos un herido!', 'Temos um ferido!'],
    ['двохсотий', 'dvokhsotyi', '“200” — killed in action (radio code)', '«200» — muerto (código)', '«200» — morto (código)', '03'],
    ['важкий', 'vazhkyi', 'critical / severe (casualty)', 'grave', 'grave', '03'],
    ['легкий', 'lehkyi', 'light / walking (casualty)', 'leve', 'leve', '03'],
    ['кров', 'krov', 'blood', 'sangre', 'sangue', '03'],
    ['рана', 'rana', 'wound', 'herida', 'ferida', '03'],
    ['бинт', 'bynt', 'bandage', 'venda', 'atadura', '03'],
    ['перев’язка', 'pereviazka', 'dressing (a wound)', 'vendaje', 'curativo', '03'],
    ['знеболювальне', 'zneboliuvalne', 'painkiller', 'analgésico', 'analgésico', '03'],
    ['шок', 'shok', 'shock', 'shock', 'choque', '03'],
    ['контузія', 'kontuziia', 'concussion / blast injury', 'conmoción', 'concussão', '03'],
    ['опік', 'opik', 'burn', 'quemadura', 'queimadura', '03'],
    ['перелом', 'perelom', 'fracture', 'fractura', 'fratura', '03'],
    ['цілий', 'tsilyi', 'unhurt / intact', 'ileso', 'ileso', '03'],
    ['голова', 'holova', 'head', 'cabeza', 'cabeça', '03'],
    ['шия', 'shyia', 'neck', 'cuello', 'pescoço', '03'],
    ['груди', 'hrudy', 'chest', 'pecho', 'peito', '03'],
    ['живіт', 'zhyvit', 'stomach / abdomen', 'abdomen', 'abdômen', '03'],
    ['спина', 'spyna', 'back', 'espalda', 'costas', '03'],
    ['притомний', 'prytomnyi', 'conscious', 'consciente', 'consciente', '03'],
    ['непритомний', 'neprytomnyi', 'unconscious', 'inconsciente', 'inconsciente', '03'],
    ['пульс', 'puls', 'pulse', 'pulso', 'pulso', '03'],
    ['Ти мене чуєш?', 'ty mene chuiesh', 'Can you hear me?', '¿Me oyes?', 'Você me ouve?', '03'],
    ['Де болить?', 'de bolyt', 'Where does it hurt?', '¿Dónde te duele?', 'Onde dói?', '03'],
    ['Тримайся!', 'trymaisia', 'Hang in there!', '¡Aguanta!', 'Aguenta!', '03'],
    ['час накладання', 'chas nakladannia', 'time applied (write it on the tourniquet)', 'hora de colocación', 'hora de aplicação', '03'],
    ['евак', 'evak', 'evac (short form)', 'evacuación (corto)', 'evacuação (curto)', '03'],
    ['стабпункт', 'stabpunkt', 'stabilisation point', 'punto de estabilización', 'ponto de estabilização', '03'],
    ['шпиталь', 'shpytal', 'military hospital', 'hospital militar', 'hospital militar', '03'],

    ['зброя', 'zbroia', 'weapon', 'arma', 'arma', '04', 'Зброю на землю!', 'Weapon on the ground!', '¡Arma al suelo!', 'Arma no chão!'],
    ['набої', 'naboi', 'rounds / ammo', 'munición', 'munição', '04'],
    ['магазин', 'mahazyn', 'magazine', 'cargador', 'carregador', '04'],
    ['шолом', 'sholom', 'helmet', 'casco', 'capacete', '04'],
    ['бронежилет', 'bronezhylet', 'body armour', 'chaleco antibalas', 'colete balístico', '04'],
    ['рація', 'ratsiia', 'radio', 'radio', 'rádio', '04'],
    ['дрон', 'dron', 'drone / UAV', 'dron', 'drone', '04'],
    ['дим', 'dym', 'smoke', 'humo', 'fumaça', '04'],
    ['ліхтар', 'likhtar', 'torch / flashlight', 'linterna', 'lanterna', '04'],
    ['автомат', 'avtomat', 'assault rifle', 'fusil de asalto', 'fuzil de assalto', '04'],
    ['кулемет', 'kulemet', 'machine gun', 'ametralladora', 'metralhadora', '04'],
    ['граната', 'hranata', 'grenade', 'granada', 'granada', '04'],
    ['міна', 'mina', 'mine / mortar round', 'mina', 'mina', '04'],
    ['снаряд', 'snariad', 'shell (artillery)', 'proyectil', 'projétil', '04'],
    ['каска', 'kaska', 'helmet (colloquial)', 'casco (coloquial)', 'capacete (coloquial)', '04'],
    ['плитоноска', 'plytonoska', 'plate carrier', 'portaplacas', 'porta-placas', '04'],
    ['розгрузка', 'rozhruzka', 'chest rig', 'chaleco portaequipo', 'colete tático', '04'],
    ['берці', 'bertsi', 'combat boots', 'botas', 'coturnos', '04'],
    ['рюкзак', 'riukzak', 'backpack', 'mochila', 'mochila', '04'],
    ['спальник', 'spalnyk', 'sleeping bag', 'saco de dormir', 'saco de dormir', '04'],
    ['каремат', 'karemat', 'sleeping mat', 'esterilla', 'isolante térmico', '04'],
    ['тепловізор', 'teplovizor', 'thermal imager', 'visor térmico', 'visor térmico', '04'],
    ['прилад нічного бачення', 'prylad nichnoho bachennia', 'night-vision device', 'visor nocturno', 'visor noturno', '04'],
    ['навушники', 'navushnyky', 'ear protection / headset', 'auriculares / protección auditiva', 'fones / proteção auditiva', '04'],
    ['окуляри', 'okuliary', 'eye protection / glasses', 'gafas', 'óculos', '04'],
    ['лопата', 'lopata', 'shovel', 'pala', 'pá', '04'],
    ['генератор', 'henerator', 'generator', 'generador', 'gerador', '04'],
    ['павербанк', 'paverbank', 'power bank', 'batería externa', 'bateria portátil', '04'],
    ['акумулятор', 'akumuliator', 'battery (rechargeable)', 'batería', 'bateria', '04'],
    ['батарейки', 'batareiky', 'batteries (disposable)', 'pilas', 'pilhas', '04'],
    ['ремінь', 'remin', 'belt / sling', 'correa / cinturón', 'cinto / bandoleira', '04'],
    ['фляга', 'fliaha', 'canteen', 'cantimplora', 'cantil', '04'],
    ['ніж', 'nizh', 'knife', 'cuchillo', 'faca', '04'],
    ['мапа', 'mapa', 'map', 'mapa', 'mapa', '04'],
    ['компас', 'kompas', 'compass', 'brújula', 'bússola', '04'],

    ['ліворуч', 'livoruch', 'to the left', 'a la izquierda', 'à esquerda', '05'],
    ['праворуч', 'pravoruch', 'to the right', 'a la derecha', 'à direita', '05'],
    ['прямо', 'priamo', 'straight ahead', 'todo recto', 'em frente', '05'],
    ['назад', 'nazad', 'back', 'atrás', 'para trás', '05'],
    ['північ', 'pivnich', 'north', 'norte', 'norte', '05'],
    ['двісті метрів', 'dvisti metriv', 'two hundred metres', 'doscientos metros', 'duzentos metros', '05'],
    ['поруч', 'poruch', 'nearby', 'cerca', 'perto', '05'],
    ['південь', 'pivden', 'south', 'sur', 'sul', '05'],
    ['схід', 'skhid', 'east', 'este', 'leste', '05'],
    ['захід', 'zakhid', 'west', 'oeste', 'oeste', '05'],
    ['вгору', 'vhoru', 'up', 'arriba', 'para cima', '05'],
    ['вниз', 'vnyz', 'down', 'abajo', 'para baixo', '05'],
    ['тут', 'tut', 'here', 'aquí', 'aqui', '05'],
    ['там', 'tam', 'there', 'allí', 'ali', '05'],
    ['далеко', 'daleko', 'far', 'lejos', 'longe', '05'],
    ['близько', 'blyzko', 'close / near', 'cerca', 'perto', '05'],
    ['п’ятдесят метрів', 'piatdesiat metriv', 'fifty metres', 'cincuenta metros', 'cinquenta metros', '05'],
    ['сто метрів', 'sto metriv', 'one hundred metres', 'cien metros', 'cem metros', '05'],
    ['кілометр', 'kilometr', 'kilometre', 'kilómetro', 'quilômetro', '05'],
    ['на дванадцяту', 'na dvanadtsiatu', 'at twelve o’clock (direction)', 'a las doce (dirección)', 'às doze horas (direção)', '05', 'Противник на дванадцяту, триста метрів.', 'Enemy at twelve o’clock, three hundred metres.', 'Enemigo a las doce, trescientos metros.', 'Inimigo às doze horas, trezentos metros.'],
    ['на третю', 'na tretiu', 'at three o’clock', 'a las tres', 'às três horas', '05'],
    ['на дев’яту', 'na deviatu', 'at nine o’clock', 'a las nueve', 'às nove horas', '05'],
    ['Де?', 'de', 'Where?', '¿Dónde?', 'Onde?', '05'],
    ['Куди?', 'kudy', 'Where to?', '¿Adónde?', 'Para onde?', '05'],
    ['Звідки?', 'zvidky', 'Where from?', '¿De dónde?', 'De onde?', '05'],
    ['дорога', 'doroha', 'road', 'camino / carretera', 'estrada', '05'],
    ['міст', 'mist', 'bridge', 'puente', 'ponte', '05'],
    ['річка', 'richka', 'river', 'río', 'rio', '05'],
    ['ліс', 'lis', 'forest', 'bosque', 'floresta', '05'],
    ['посадка', 'posadka', 'tree line (planted strip)', 'línea de árboles', 'linha de árvores', '05'],
    ['поле', 'pole', 'field', 'campo', 'campo', '05'],
    ['село', 'selo', 'village', 'pueblo', 'vila / aldeia', '05'],
    ['будинок', 'budynok', 'house / building', 'casa / edificio', 'casa / prédio', '05'],
    ['окоп', 'okop', 'trench / foxhole', 'trinchera', 'trincheira', '05'],
    ['бліндаж', 'blindazh', 'dugout / bunker', 'búnker / refugio', 'abrigo / bunker', '05'],
    ['позиція', 'pozytsiia', 'position', 'posición', 'posição', '05'],
    ['тил', 'tyl', 'the rear', 'la retaguardia', 'a retaguarda', '05'],
    ['рубіж', 'rubizh', 'line (firing line, boundary)', 'línea (de tiro)', 'linha (de tiro)', '05'],

    ['доповідаю', 'dopovidaiu', 'reporting (I report)', 'informo', 'reporto', '06'],
    ['наказ', 'nakaz', 'order', 'orden', 'ordem', '06'],
    ['позивний', 'pozyvnyi', 'call sign', 'indicativo', 'indicativo', '06'],
    ['посвідчення', 'posvidchennia', 'ID card', 'identificación', 'identificação', '06'],
    ['час', 'chas', 'time', 'hora', 'hora', '06'],
    ['паспорт', 'pasport', 'passport', 'pasaporte', 'passaporte', '06'],
    ['квиток', 'kvytok', 'ticket', 'billete', 'bilhete', '06', 'Ось мій квиток.', 'Here is my ticket.', 'Aquí está mi billete.', 'Aqui está meu bilhete.'],
    ['кордон', 'kordon', 'border', 'frontera', 'fronteira', '06'],
    ['на зв’язку', 'na zviazku', 'on the radio / standing by', 'a la escucha', 'na escuta', '06'],
    ['прийняв', 'pryiniav', 'copy / roger', 'recibido', 'entendido / copiado', '06'],
    ['прийом', 'pryiom', 'over (radio)', 'cambio', 'câmbio', '06'],
    ['кінець зв’язку', 'kinets zviazku', 'out (radio)', 'corto', 'desligo', '06'],
    ['Як чуєш?', 'yak chuiesh', 'How do you read me?', '¿Cómo me recibes?', 'Como me recebe?', '06'],
    ['Чую добре.', 'chuiu dobre', 'Reading you loud and clear.', 'Te recibo bien.', 'Recebo bem.', '06'],
    ['Чую погано.', 'chuiu pohano', 'Reading you badly.', 'Te recibo mal.', 'Recebo mal.', '06'],
    ['Повтори.', 'povtory', 'Say again. (informal)', 'Repite.', 'Repita.', '06'],
    ['доповідь', 'dopovid', 'report (noun)', 'informe', 'relatório', '06'],
    ['рапорт', 'raport', 'written report / formal request', 'informe escrito / solicitud', 'requerimento (militar)', '06'],
    ['координати', 'koordynaty', 'coordinates', 'coordenadas', 'coordenadas', '06'],
    ['противник', 'protyvnyk', 'enemy', 'enemigo', 'inimigo', '06'],
    ['ворог', 'voroh', 'enemy (colloquial)', 'enemigo', 'inimigo', '06'],
    ['завдання', 'zavdannia', 'task / mission', 'misión / tarea', 'missão / tarefa', '06'],
    ['ротація', 'rotatsiia', 'rotation', 'rotación', 'rotação', '06'],
    ['відпустка', 'vidpustka', 'leave', 'permiso', 'licença', '06'],
    ['контракт', 'kontrakt', 'contract', 'contrato', 'contrato', '06'],
    ['заява', 'zaiava', 'application / written statement', 'solicitud', 'declaração / pedido', '06'],
    ['підпис', 'pidpys', 'signature', 'firma', 'assinatura', '06'],
    ['штаб', 'shtab', 'headquarters', 'cuartel general', 'quartel-general', '06'],
    ['дозвіл', 'dozvil', 'permission / permit', 'permiso', 'permissão', '06'],
    ['номер', 'nomer', 'number', 'número', 'número', '06'],
    ['прізвище', 'prizvyshche', 'surname', 'apellido', 'sobrenome', '06'],
    ['ім’я', 'imia', 'first name', 'nombre', 'nome', '06'],
    ['дата народження', 'data narodzhennia', 'date of birth', 'fecha de nacimiento', 'data de nascimento', '06'],
    ['група крові', 'hrupa krovi', 'blood type', 'grupo sanguíneo', 'tipo sanguíneo', '06', 'Група крові — перша позитивна.', 'Blood type O positive.', 'Grupo sanguíneo O positivo.', 'Tipo sanguíneo O positivo.'],

    ['вода', 'voda', 'water', 'agua', 'água', '07'],
    ['їжа', 'yizha', 'food', 'comida', 'comida', '07'],
    ['спати', 'spaty', 'to sleep', 'dormir', 'dormir', '07'],
    ['холодно', 'kholodno', 'cold (it is)', 'hace frío', 'está frio', '07'],
    ['укриття', 'ukryttia', 'shelter / cover', 'refugio', 'abrigo', '07'],
    ['дякую', 'diakuiu', 'thank you', 'gracias', 'obrigado', '07'],
    ['будь ласка', 'bud laska', 'please / you’re welcome', 'por favor', 'por favor', '07'],
    ['вибачте', 'vybachte', 'excuse me / sorry', 'disculpe', 'desculpe', '07', 'Вибачте, де мій вагон?', 'Excuse me, where is my carriage?', 'Disculpe, ¿dónde está mi vagón?', 'Desculpe, onde está meu vagão?'],
    ['потяг', 'potiah', 'train', 'tren', 'trem', '07'],
    ['вагон', 'vahon', 'carriage / train car', 'vagón', 'vagão', '07'],
    ['місце', 'mistse', 'seat / place', 'asiento', 'assento', '07'],
    ['волонтер', 'volonter', 'volunteer', 'voluntario', 'voluntário', '07'],
    ['Привіт!', 'pryvit', 'Hi!', '¡Hola!', 'Oi!', '07'],
    ['Доброго дня!', 'dobroho dnia', 'Good day!', '¡Buenos días!', 'Bom dia!', '07'],
    ['Добраніч.', 'dobranich', 'Good night.', 'Buenas noches.', 'Boa noite.', '07'],
    ['До побачення.', 'do pobachennia', 'Goodbye.', 'Adiós.', 'Tchau / Até logo.', '07'],
    ['Як справи?', 'yak spravy', 'How are things?', '¿Qué tal?', 'Como vai?', '07'],
    ['Добре.', 'dobre', 'Good. / Fine.', 'Bien.', 'Bem.', '07'],
    ['Погано.', 'pohano', 'Bad.', 'Mal.', 'Mal.', '07'],
    ['Все добре.', 'vse dobre', "All good. / It's fine.", 'Todo bien.', 'Tudo bem.', '07'],
    ['Мене звати…', 'mene zvaty', 'My name is…', 'Me llamo…', 'Meu nome é…', '07'],
    ['Я з…', 'ya z', 'I am from…', 'Soy de…', 'Eu sou de…', '07', 'Я з Колумбії.', 'I am from Colombia.', 'Soy de Colombia.', 'Sou da Colômbia.'],
    ['Я не розумію.', 'ya ne rozumiiu', "I don't understand.", 'No entiendo.', 'Não entendo.', '07'],
    ['Я розумію.', 'ya rozumiiu', 'I understand.', 'Entiendo.', 'Entendo.', '07'],
    ['Допоможи!', 'dopomozhy', 'Help me!', '¡Ayúdame!', 'Me ajude!', '07'],
    ['Скільки?', 'skilky', 'How many? / How much?', '¿Cuánto?', 'Quanto?', '07'],
    ['Де туалет?', 'de tualet', 'Where is the toilet?', '¿Dónde está el baño?', 'Onde é o banheiro?', '07'],
    ['їдальня', 'yidalnia', 'mess hall / canteen', 'comedor', 'refeitório', '07'],
    ['душ', 'dush', 'shower', 'ducha', 'chuveiro', '07'],
    ['чай', 'chai', 'tea', 'té', 'chá', '07'],
    ['кава', 'kava', 'coffee', 'café', 'café', '07'],
    ['хліб', 'khlib', 'bread', 'pan', 'pão', '07'],
    ['сигарети', 'syharety', 'cigarettes', 'cigarrillos', 'cigarros', '07'],
    ['ковдра', 'kovdra', 'blanket', 'manta', 'cobertor', '07'],
    ['тепло', 'teplo', 'warm (it is)', 'hace calor', 'está quente', '07'],
    ['гаряче', 'hariache', 'hot (careful!)', 'está caliente', 'está quente (cuidado)', '07'],
    ['дуже', 'duzhe', 'very', 'muy', 'muito', '07'],
    ['трохи', 'trokhy', 'a little', 'un poco', 'um pouco', '07'],
    ['чергування', 'cherhuvannia', 'duty shift', 'turno de guardia', 'turno de serviço', '07'],
    ['варта', 'varta', 'guard / sentry duty', 'guardia', 'guarda / sentinela', '07'],
    ['шикування', 'shykuvannia', 'formation (parade)', 'formación', 'formatura', '07'],
    ['підйом', 'pidiom', 'reveille / wake-up', 'diana', 'alvorada', '07'],
    ['перерва', 'pererva', 'break', 'descanso', 'intervalo', '07'],
    ['телефон', 'telefon', 'phone', 'teléfono', 'telefone', '07'],
    ['зв’язок', 'zviazok', 'signal / comms', 'señal / comunicación', 'sinal / comunicação', '07'],

    ['нуль', 'nul', 'zero (also: “the zero line”, the front)', 'cero (también: «la línea cero», el frente)', 'zero (também: «a linha zero», o front)', '08'],
    ['один', 'odyn', 'one', 'uno', 'um', '08'],
    ['два', 'dva', 'two', 'dos', 'dois', '08'],
    ['три', 'try', 'three', 'tres', 'três', '08'],
    ['чотири', 'chotyry', 'four', 'cuatro', 'quatro', '08'],
    ['п’ять', 'piat', 'five', 'cinco', 'cinco', '08'],
    ['шість', 'shist', 'six', 'seis', 'seis', '08'],
    ['сім', 'sim', 'seven', 'siete', 'sete', '08'],
    ['вісім', 'visim', 'eight', 'ocho', 'oito', '08'],
    ['дев’ять', 'deviat', 'nine', 'nueve', 'nove', '08'],
    ['десять', 'desiat', 'ten', 'diez', 'dez', '08'],
    ['двадцять', 'dvadtsiat', 'twenty', 'veinte', 'vinte', '08'],
    ['тридцять', 'trydtsiat', 'thirty', 'treinta', 'trinta', '08'],
    ['п’ятдесят', 'piatdesiat', 'fifty', 'cincuenta', 'cinquenta', '08'],
    ['сто', 'sto', 'one hundred', 'cien', 'cem', '08'],
    ['тисяча', 'tysiacha', 'one thousand', 'mil', 'mil', '08'],
    ['перший', 'pershyi', 'first', 'primero', 'primeiro', '08'],
    ['другий', 'druhyi', 'second', 'segundo', 'segundo', '08'],
    ['третій', 'tretii', 'third', 'tercero', 'terceiro', '08'],
    ['година', 'hodyna', 'hour', 'hora', 'hora', '08'],
    ['хвилина', 'khvylyna', 'minute', 'minuto', 'minuto', '08'],
    ['зараз', 'zaraz', 'now', 'ahora', 'agora', '08'],
    ['потім', 'potim', 'later', 'después', 'depois', '08'],
    ['сьогодні', 'sohodni', 'today', 'hoy', 'hoje', '08'],
    ['завтра', 'zavtra', 'tomorrow', 'mañana', 'amanhã', '08'],
    ['вчора', 'vchora', 'yesterday', 'ayer', 'ontem', '08'],
    ['ранок', 'ranok', 'morning', 'mañana (parte del día)', 'manhã', '08'],
    ['вечір', 'vechir', 'evening', 'tarde / noche', 'fim de tarde / noite', '08'],
    ['ніч', 'nich', 'night', 'noche', 'noite', '08'],
    ['О котрій?', 'o kotrii', 'At what time?', '¿A qué hora?', 'A que horas?', '08', 'О котрій шикування?', 'What time is formation?', '¿A qué hora es la formación?', 'A que horas é a formatura?'],
    ['о шостій', 'o shostii', 'at six o’clock', 'a las seis', 'às seis', '08'],
    ['через п’ять хвилин', 'cherez piat khvylyn', 'in five minutes', 'en cinco minutos', 'em cinco minutos', '08'],
  ];

  const TERMS = ROWS.map(([uk, tr, en, es, pt, sec, exUk, exEn, exEs, exPt]) => ({
    uk, tr, en, es, pt, sec,
    example: exUk ? { uk: exUk, en: exEn, es: exEs, pt: exPt } : null,
    letter: uk[0].toUpperCase(),
  }));

  // Progress shown on track cards is computed live from per-scenario
  // localStorage (see app.js) — no hardcoded lesson counts.
  // Title/desc are per-language; `uk` stays fixed.
  const TRACKS = [
    {
      no: '01', level: 'A0 → A1', uk: 'Перший тиждень',
      en: 'First week in a unit', es: 'Primera semana en la unidad', pt: 'Primeira semana na unidade',
      desc: {
        en: 'Greetings, ranks, forms of address, yes/no/understood, basic needs. Day one survival language.',
        es: 'Saludos, rangos, tratamientos, sí/no/entendido, necesidades básicas. Lenguaje de supervivencia para el primer día.',
        pt: 'Saudações, patentes, formas de tratamento, sim/não/entendido, necessidades básicas. Linguagem de sobrevivência para o primeiro dia.',
      },
      tone: 'yellow', tag: 'ТРЕК 01',
    },
    {
      no: '02', level: 'A1', uk: 'На полігоні',
      en: 'On the training ground', es: 'En el campo de entrenamiento', pt: 'No campo de treinamento',
      desc: {
        en: 'Drill commands, weapons handling vocabulary, safety calls, directions and distances.',
        es: 'Voces de mando, vocabulario de manejo de armas, avisos de seguridad, direcciones y distancias.',
        pt: 'Vozes de comando, vocabulário de manuseio de armas, avisos de segurança, direções e distâncias.',
      },
      tone: 'cream', tag: 'ТРЕК 02',
    },
    {
      no: '03', level: 'A1 → A2', uk: 'Медична мова',
      en: 'Medical language', es: 'Lenguaje médico', pt: 'Linguagem médica',
      desc: {
        en: 'Casualty calls, MARCH vocabulary, body parts, evacuation phrases. For medics and everyone else.',
        es: 'Avisos de bajas, vocabulario MARCH, partes del cuerpo, frases de evacuación. Para sanitarios y para todos.',
        pt: 'Chamados de baixa, vocabulário MARCH, partes do corpo, frases de evacuação. Para socorristas e para todos.',
      },
      tone: 'cream', tag: 'ТРЕК 03',
    },
    {
      no: '04', level: 'B1', uk: 'Мова інструктора',
      en: "Instructor's toolkit", es: 'Herramientas del instructor', pt: 'Kit do instrutor',
      desc: {
        en: 'Teaching through an interpreter, giving corrections, classroom + range instructions in Ukrainian.',
        es: 'Enseñar con intérprete, dar correcciones, instrucciones de aula y de campo de tiro en ucraniano.',
        pt: 'Ensinar com intérprete, dar correções, instruções de sala e de estande de tiro em ucraniano.',
      },
      tone: 'blue', tag: 'ТРЕК 04',
      tagNote: { en: 'FOR INSTRUCTORS', es: 'PARA INSTRUCTORES', pt: 'PARA INSTRUTORES' },
    },
    {
      no: '05', level: 'A1', uk: 'У дорозі',
      en: 'Getting there', es: 'El viaje', pt: 'A viagem',
      desc: {
        en: 'Border control, trains, tickets, asking for help — the trip in, before day one.',
        es: 'Control fronterizo, trenes, billetes, pedir ayuda — el viaje de ida, antes del primer día.',
        pt: 'Controle de fronteira, trens, bilhetes, pedir ajuda — a viagem de ida, antes do primeiro dia.',
      },
      tone: 'cream', tag: 'ТРЕК 05',
    },
    {
      no: '06', level: 'A2', uk: 'Радіозв’язок',
      en: 'Radio comms', es: 'Radiocomunicaciones', pt: 'Comunicações de rádio',
      desc: {
        en: 'Call signs, radio checks, reporting position and contact, calling in a casualty. Short, in order, over.',
        es: 'Indicativos, comprobaciones de radio, informar posición y contacto, avisar de una baja. Corto, en orden, cambio.',
        pt: 'Indicativos, teste de rádio, reportar posição e contato, informar uma baixa. Curto, em ordem, câmbio.',
      },
      tone: 'blue', tag: 'ТРЕК 06',
    },
    {
      no: '07', level: 'A1 → A2', uk: 'На позиції',
      en: 'On position', es: 'En posición', pt: 'Na posição',
      desc: {
        en: 'Moving in at night, drone warnings, contact and pulling back — the words that keep you alive when nobody around speaks your language.',
        es: 'Entrar de noche, avisos de dron, contacto y retirada — las palabras que te mantienen vivo cuando nadie habla tu idioma.',
        pt: 'Entrar à noite, avisos de drone, contato e recuo — as palavras que mantêm você vivo quando ninguém fala sua língua.',
      },
      tone: 'yellow', tag: 'ТРЕК 07',
    },
  ];

  /* Scenarios are journeys: an ordered list of scenes, each scene an ordered
     list of typed steps. Progress is stored per scene as `pk-j-<id>-<sceneId>`.

     Step types (see the scenario engine in app.js):
       line      { lang:'УК'|'EN', uk, tr, en, es, pt } — dialogue; УК is the
                 Ukrainian speaker, EN is the volunteer's turn (badge follows
                 the picked site language). uk/tr teach the Ukrainian; en/es/pt
                 are glosses.
       speak     { uk, tr, en, es, pt } — the learner must say `uk` out loud;
                 validated by speech recognition where available, always
                 skippable.
       choice    { q:{en,es,pt}, options:[{label, right?}] } — multiple choice.
                 Labels stay plain strings; Cyrillic labels are played as audio
                 on a correct answer (and harvested by scripts/tts.mjs).
       translate { uk, tr, keywords:{en,es,pt}, model:{en,es,pt} } — type the
                 translation in your own language, no copy-paste. `keywords` is
                 a list of concepts per language, each an array of acceptable
                 synonyms; ≥60% of concepts matched = pass. `model` is the
                 answer revealed after checking.
       info      { title:{en,es,pt}, body:{en,es,pt}, uk? } — narrative context
                 card (ticket details, what to expect…). One tap to continue.
       form      — reserved for the future document-filling course. Not built.
  */
  const SCENARIOS = [
    {
      id: 'first-week',
      track: '01',
      difficulty: 'A0',
      category: { en: 'FIRST WEEK', es: 'PRIMERA SEMANA', pt: 'PRIMEIRA SEMANA' },
      uk: 'Знайомство.', en: 'Introductions.', es: 'Presentaciones.', pt: 'Apresentações.',
      keyTerms: ['сержант', 'позивний', 'будь ласка', 'дякую'],
      scenes: [
        {
          id: 's1',
          uk: 'Знайомство.', en: 'Introductions.', es: 'Presentaciones.', pt: 'Apresentações.',
          steps: [
            { type: 'line', lang: 'УК', uk: 'Я — сержант Андрій. Позивний «Сокіл».', tr: 'ya — serzhant andrii. pozyvnyi "sokil"', en: 'I am sergeant Andrii. Call sign "Sokil".', es: 'Soy el sargento Andrii. Indicativo «Sokil».', pt: 'Sou o sargento Andrii. Indicativo «Sokil».' },
            { type: 'line', lang: 'EN', uk: 'Дуже приємно. Я — доброволець.', tr: 'duzhe pryiemno. ya — dobrovolets', en: 'Nice to meet you. I am a volunteer.', es: 'Mucho gusto. Soy voluntario.', pt: 'Muito prazer. Sou voluntário.' },
            { type: 'line', lang: 'УК', uk: 'Зрозумів. Говориш українською?', tr: 'zrozumiv. hovorysh ukrainskoiu?', en: 'Understood. Do you speak Ukrainian?', es: 'Entendido. ¿Hablas ucraniano?', pt: 'Entendido. Você fala ucraniano?' },
            { type: 'speak', uk: 'Трохи. Повільно, будь ласка.', tr: 'trokhy. povilno, bud laska', en: 'A little. Slowly, please.', es: 'Un poco. Despacio, por favor.', pt: 'Um pouco. Devagar, por favor.' },
            { type: 'line', lang: 'УК', uk: 'Добре. Дякую, побратиме!', tr: 'dobre. diakuiu, pobratyme!', en: 'Good. Thank you, brother!', es: 'Bien. ¡Gracias, hermano!', pt: 'Bom. Obrigado, irmão!' },
            { type: 'choice',
              q: { en: 'How do you say “thank you”?', es: '¿Cómo se dice «gracias»?', pt: 'Como se diz «obrigado»?' },
              options: [
                { label: 'дякую', right: true },
                { label: 'вода' },
                { label: 'наказ' },
              ] },
          ],
        },
        {
          id: 'routine',
          uk: 'Розпорядок.', en: 'Daily routine.', es: 'La rutina.', pt: 'A rotina.',
          steps: [
            { type: 'info',
              title: { en: 'Day one', es: 'Primer día', pt: 'Primeiro dia' },
              body: {
                en: 'Your first morning. Formation («шикування») is at six; food is in the «їдальня». You will hear numbers and times all day, and the sergeant will not slow down for you — so ask, in Ukrainian.',
                es: 'Tu primera mañana. La formación («шикування») es a las seis; la comida está en la «їдальня». Oirás números y horas todo el día, y el sargento no irá más despacio por ti — así que pregunta, en ucraniano.',
                pt: 'Sua primeira manhã. A formatura («шикування») é às seis; a comida fica no «їдальня». Você vai ouvir números e horas o dia todo, e o sargento não vai desacelerar por você — então pergunte, em ucraniano.',
              } },
            { type: 'line', lang: 'УК', uk: 'Підйом! Шикування о шостій.', tr: 'pidiom! shykuvannia o shostii', en: 'Wake up! Formation at six.', es: '¡Arriba! Formación a las seis.', pt: 'Alvorada! Formatura às seis.' },
            { type: 'speak', uk: 'О котрій шикування?', tr: 'o kotrii shykuvannia', en: 'What time is formation?', es: '¿A qué hora es la formación?', pt: 'A que horas é a formatura?' },
            { type: 'line', lang: 'УК', uk: 'О шостій. Через п’ять хвилин.', tr: 'o shostii. cherez piat khvylyn', en: 'At six. In five minutes.', es: 'A las seis. En cinco minutos.', pt: 'Às seis. Em cinco minutos.' },
            { type: 'speak', uk: 'Так точно! Де їдальня?', tr: 'tak tochno! de yidalnia', en: 'Yes, sir! Where is the mess hall?', es: '¡Sí, señor! ¿Dónde está el comedor?', pt: 'Sim, senhor! Onde é o refeitório?' },
            { type: 'line', lang: 'УК', uk: 'Прямо і праворуч. Потім — до мене.', tr: 'priamo i pravoruch. potim — do mene', en: 'Straight ahead and to the right. Then — to me.', es: 'Todo recto y a la derecha. Después — a mí.', pt: 'Em frente e à direita. Depois — a mim.' },
            { type: 'choice',
              q: { en: 'What time is formation?', es: '¿A qué hora es la formación?', pt: 'A que horas é a formatura?' },
              options: [
                { label: '5:00' },
                { label: '6:00', right: true },
                { label: '7:00' },
              ] },
            { type: 'translate', uk: 'Через п’ять хвилин.', tr: 'cherez piat khvylyn',
              keywords: {
                en: [['five', '5'], ['minute', 'minutes']],
                es: [['cinco', '5'], ['minuto', 'minutos']],
                pt: [['cinco', '5'], ['minuto', 'minutos']],
              },
              model: { en: 'In five minutes.', es: 'En cinco minutos.', pt: 'Em cinco minutos.' } },
          ],
        },
        {
          id: 'yes-sir',
          uk: 'Так точно.', en: 'Yes, sir.', es: 'Sí, señor.', pt: 'Sim, senhor.',
          steps: [
            { type: 'info',
              title: { en: 'Yes, no, understood', es: 'Sí, no, entendido', pt: 'Sim, não, entendido' },
              body: {
                en: 'Three answers cover most of day one: «Так точно!» (yes, sir), «Ніяк ні!» (no, sir), «Зрозумів» (understood). If you did not understand, say so: «Не зрозумів. Повільніше, будь ласка». Nobody will be angry — guessing is what gets people hurt.',
                es: 'Tres respuestas cubren casi todo el primer día: «Так точно!» (sí, señor), «Ніяк ні!» (no, señor), «Зрозумів» (entendido). Si no entendiste, dilo: «Не зрозумів. Повільніше, будь ласка». Nadie se enfadará — adivinar es lo que hiere a la gente.',
                pt: 'Três respostas cobrem quase todo o primeiro dia: «Так точно!» (sim, senhor), «Ніяк ні!» (não, senhor), «Зрозумів» (entendido). Se não entendeu, diga: «Не зрозумів. Повільніше, будь ласка». Ninguém vai ficar bravo — adivinhar é o que machuca as pessoas.',
              } },
            { type: 'line', lang: 'УК', uk: 'Ти зрозумів наказ?', tr: 'ty zrozumiv nakaz', en: 'Did you understand the order?', es: '¿Entendiste la orden?', pt: 'Você entendeu a ordem?' },
            { type: 'speak', uk: 'Не зрозумів. Повільніше, будь ласка.', tr: 'ne zrozumiv. povilnishe, bud laska', en: "I didn't understand. Slower, please.", es: 'No entendí. Más despacio, por favor.', pt: 'Não entendi. Mais devagar, por favor.' },
            { type: 'line', lang: 'УК', uk: 'Добре. Завтра — варта. О шостій ранку. Зрозумів?', tr: 'dobre. zavtra — varta. o shostii ranku. zrozumiv?', en: 'OK. Tomorrow — guard duty. At six in the morning. Understood?', es: 'Bien. Mañana — guardia. A las seis de la mañana. ¿Entendido?', pt: 'Certo. Amanhã — guarda. Às seis da manhã. Entendido?' },
            { type: 'speak', uk: 'Так точно! Завтра, варта, о шостій.', tr: 'tak tochno! zavtra, varta, o shostii', en: 'Yes, sir! Tomorrow, guard duty, at six.', es: '¡Sí, señor! Mañana, guardia, a las seis.', pt: 'Sim, senhor! Amanhã, guarda, às seis.' },
            { type: 'line', lang: 'УК', uk: 'Молодець! Розійтись!', tr: 'molodets! roziitys!', en: 'Well done! Dismissed!', es: '¡Bien hecho! ¡Rompan filas!', pt: 'Muito bem! Debandar!' },
            { type: 'choice',
              q: { en: 'You did not understand. What do you say?', es: 'No entendiste. ¿Qué dices?', pt: 'Você não entendeu. O que diz?' },
              options: [
                { label: 'Так точно!' },
                { label: 'Не зрозумів.', right: true },
                { label: 'Відбій!' },
              ] },
          ],
        },
      ],
    },
    {
      id: 'range',
      track: '02',
      difficulty: 'A1',
      category: { en: 'TRAINING GROUND', es: 'CAMPO DE ENTRENAMIENTO', pt: 'CAMPO DE TREINAMENTO' },
      uk: 'На стрільбищі.', en: 'On the range.', es: 'En el campo de tiro.', pt: 'No estande de tiro.',
      keyTerms: ['зброя', 'магазин', 'набої', 'Вогонь!'],
      scenes: [
        {
          id: 's1',
          uk: 'На стрільбищі.', en: 'On the range.', es: 'En el campo de tiro.', pt: 'No estande de tiro.',
          steps: [
            { type: 'line', lang: 'УК', uk: 'Зброю на землю! Магазин від’єднати!', tr: 'zbroiu na zemliu! mahazyn vidiednaty!', en: 'Weapon on the ground! Detach the magazine!', es: '¡Arma al suelo! ¡Retira el cargador!', pt: 'Arma no chão! Retire o carregador!' },
            { type: 'speak', uk: 'Магазин знято. Зброя розряджена.', tr: 'mahazyn zniato. zbroia rozriadzhena', en: 'Magazine off. Weapon is clear.', es: 'Cargador fuera. Arma descargada.', pt: 'Carregador fora. Arma descarregada.' },
            { type: 'line', lang: 'УК', uk: 'Готовий? Набої — двадцять.', tr: 'hotovyi? naboi — dvadtsiat', en: 'Ready? Twenty rounds.', es: '¿Listo? Veinte cartuchos.', pt: 'Pronto? Vinte cartuchos.' },
            { type: 'line', lang: 'УК', uk: 'Вогонь!', tr: 'vohon!', en: 'Fire!', es: '¡Fuego!', pt: 'Fogo!' },
            { type: 'line', lang: 'УК', uk: 'Стій! Не стріляти!', tr: 'stii! ne striliaty!', en: 'Halt! Cease fire!', es: '¡Alto! ¡Alto el fuego!', pt: 'Alto! Cessar fogo!' },
            { type: 'choice',
              q: { en: 'How do you shout “Fire!”?', es: '¿Cómo se grita «¡Fuego!»?', pt: 'Como se grita «Fogo!»?' },
              options: [
                { label: 'Стій!' },
                { label: 'Вогонь!', right: true },
                { label: 'Лягай!' },
              ] },
          ],
        },
        {
          id: 'safety',
          uk: 'Безпека.', en: 'Safety.', es: 'Seguridad.', pt: 'Segurança.',
          steps: [
            { type: 'info',
              title: { en: 'Range safety words', es: 'Palabras de seguridad', pt: 'Palavras de segurança' },
              body: {
                en: 'Everything on the range is shouted. Three you must react to instantly: «Стій!» (halt), «Не стріляти!» (cease fire), «На запобіжник!» (safety on). And one you must be able to shout yourself: «Осічка!» — misfire.',
                es: 'En el campo de tiro todo se grita. Tres a las que debes reaccionar al instante: «Стій!» (alto), «Не стріляти!» (alto el fuego), «На запобіжник!» (seguro puesto). Y una que debes saber gritar tú: «Осічка!» — fallo de tiro.',
                pt: 'No estande tudo é gritado. Três às quais você deve reagir na hora: «Стій!» (alto), «Не стріляти!» (cessar fogo), «На запобіжник!» (trava). E uma que você mesmo precisa saber gritar: «Осічка!» — falha de tiro.',
              } },
            { type: 'line', lang: 'УК', uk: 'На рубіж! Заряджай!', tr: 'na rubizh! zariadzhai!', en: 'To the firing line! Load!', es: '¡A la línea de tiro! ¡Carguen!', pt: 'À linha de tiro! Carregar!' },
            { type: 'speak', uk: 'Осічка!', tr: 'osichka', en: 'Misfire!', es: '¡Fallo de tiro!', pt: 'Falha de tiro!' },
            { type: 'line', lang: 'УК', uk: 'Стій! Не стріляти! На запобіжник!', tr: 'stii! ne striliaty! na zapobizhnyk!', en: 'Halt! Cease fire! Safety on!', es: '¡Alto! ¡Alto el fuego! ¡Seguro puesto!', pt: 'Alto! Cessar fogo! Trava de segurança!' },
            { type: 'speak', uk: 'Зброя на запобіжнику.', tr: 'zbroia na zapobizhnyku', en: 'Weapon is on safe.', es: 'Arma con el seguro puesto.', pt: 'Arma travada.' },
            { type: 'line', lang: 'УК', uk: 'Зброю до огляду!', tr: 'zbroiu do ohliadu!', en: 'Weapons for inspection!', es: '¡Armas para inspección!', pt: 'Armas para inspeção!' },
            { type: 'line', lang: 'EN', uk: 'Зброя розряджена.', tr: 'zbroia rozriadzhena', en: 'Weapon is clear.', es: 'Arma descargada.', pt: 'Arma descarregada.' },
            { type: 'choice',
              q: { en: 'Which shout means “cease fire”?', es: '¿Qué grito significa «alto el fuego»?', pt: 'Qual grito significa «cessar fogo»?' },
              options: [
                { label: 'Заряджай!' },
                { label: 'Не стріляти!', right: true },
                { label: 'Вогонь!' },
              ] },
          ],
        },
        {
          id: 'target',
          uk: 'Ціль.', en: 'Target.', es: 'Blanco.', pt: 'Alvo.',
          steps: [
            { type: 'info',
              title: { en: 'Clock directions', es: 'Direcciones de reloj', pt: 'Direções de relógio' },
              body: {
                en: 'Targets are called by clock face and distance: «на дванадцяту» is straight ahead, «на третю» to the right, «на дев’яту» to the left. Then the range in metres: «сто метрів», «двісті метрів». Say it back to confirm you have it.',
                es: 'Los blancos se indican por la esfera del reloj y la distancia: «на дванадцяту» es al frente, «на третю» a la derecha, «на дев’яту» a la izquierda. Luego la distancia en metros: «сто метрів», «двісті метрів». Repítelo para confirmar.',
                pt: 'Os alvos são indicados pelo relógio e pela distância: «на дванадцяту» é em frente, «на третю» à direita, «на дев’яту» à esquerda. Depois a distância em metros: «сто метрів», «двісті метрів». Repita para confirmar.',
              } },
            { type: 'line', lang: 'УК', uk: 'Ціль! На дванадцяту, сто метрів.', tr: 'tsil! na dvanadtsiatu, sto metriv', en: 'Target! Twelve o’clock, one hundred metres.', es: '¡Blanco! A las doce, cien metros.', pt: 'Alvo! Às doze horas, cem metros.' },
            { type: 'speak', uk: 'Бачу. На дванадцяту, сто метрів.', tr: 'bachu. na dvanadtsiatu, sto metriv', en: 'I see it. Twelve o’clock, one hundred metres.', es: 'Lo veo. A las doce, cien metros.', pt: 'Vejo. Às doze horas, cem metros.' },
            { type: 'line', lang: 'УК', uk: 'Друга ціль — на третю, двісті метрів.', tr: 'druha tsil — na tretiu, dvisti metriv', en: 'Second target — three o’clock, two hundred metres.', es: 'Segundo blanco — a las tres, doscientos metros.', pt: 'Segundo alvo — às três horas, duzentos metros.' },
            { type: 'speak', uk: 'Не бачу. Повторіть.', tr: 'ne bachu. povtorit', en: "I don't see it. Say again.", es: 'No lo veo. Repita.', pt: 'Não vejo. Repita.' },
            { type: 'line', lang: 'УК', uk: 'На третю. Праворуч, біля посадки.', tr: 'na tretiu. pravoruch, bilia posadky', en: 'Three o’clock. To the right, by the tree line.', es: 'A las tres. A la derecha, junto a la línea de árboles.', pt: 'Às três horas. À direita, perto da linha de árvores.' },
            { type: 'choice',
              q: { en: 'Where is «на дев’яту»?', es: '¿Dónde es «на дев’яту»?', pt: 'Onde é «на дев’яту»?' },
              options: [
                { label: 'ліворуч', right: true },
                { label: 'праворуч' },
                { label: 'прямо' },
              ] },
            { type: 'translate', uk: 'Ціль на дванадцяту, сто метрів.', tr: 'tsil na dvanadtsiatu, sto metriv',
              keywords: {
                en: [['target'], ['twelve', '12'], ['hundred', '100']],
                es: [['blanco', 'objetivo'], ['doce', '12'], ['cien', '100']],
                pt: [['alvo'], ['doze', '12'], ['cem', '100']],
              },
              model: { en: 'Target at twelve o’clock, one hundred metres.', es: 'Blanco a las doce, cien metros.', pt: 'Alvo às doze horas, cem metros.' } },
          ],
        },
      ],
    },
    {
      id: 'medical-casualty',
      track: '03',
      difficulty: 'A1',
      category: { en: 'MEDICAL', es: 'MÉDICO', pt: 'MÉDICO' },
      uk: 'Поранений.', en: 'Casualty.', es: 'Baja.', pt: 'Baixa.',
      keyTerms: ['поранений', 'медик', 'джгут', 'нога'],
      scenes: [
        {
          id: 's1',
          uk: 'Поранений.', en: 'Casualty.', es: 'Baja.', pt: 'Baixa.',
          steps: [
            { type: 'line', lang: 'УК', uk: 'Маємо пораненого! Потрібен медик!', tr: 'maiemo poranenoho! potriben medyk!', en: 'We have a casualty! We need a medic!', es: '¡Tenemos un herido! ¡Necesitamos un sanitario!', pt: 'Temos um ferido! Precisamos de um socorrista!' },
            { type: 'speak', uk: 'Куди його поранено?', tr: 'kudy yoho poraneno', en: 'Where is he hit?', es: '¿Dónde está herido?', pt: 'Onde ele foi atingido?' },
            { type: 'line', lang: 'УК', uk: 'Нога. Наклади джгут!', tr: 'noha. naklady dzhhut!', en: 'The leg. Apply a tourniquet!', es: 'La pierna. ¡Pon un torniquete!', pt: 'A perna. Aplique um torniquete!' },
            { type: 'line', lang: 'EN', uk: 'Джгут накладено. Викликаю евакуацію.', tr: 'dzhhut nakladeno. vyklykaiu evakuatsiiu', en: 'Tourniquet on. Calling for evacuation.', es: 'Torniquete puesto. Pido evacuación.', pt: 'Torniquete aplicado. Chamando evacuação.' },
            { type: 'line', lang: 'УК', uk: 'Ноші сюди! Швидше!', tr: 'noshi siudy! shvydshe!', en: 'Stretcher over here! Faster!', es: '¡La camilla aquí! ¡Más rápido!', pt: 'Maca aqui! Mais rápido!' },
            { type: 'choice',
              q: { en: 'How do you shout “tourniquet”?', es: '¿Cómo se grita «torniquete»?', pt: 'Como se grita «torniquete»?' },
              options: [
                { label: 'укриття' },
                { label: 'джгут', right: true },
                { label: 'звання' },
              ] },
          ],
        },
        {
          id: 'march',
          uk: 'Огляд.', en: 'Assessment.', es: 'Evaluación.', pt: 'Avaliação.',
          steps: [
            { type: 'info',
              title: { en: 'MARCH in Ukrainian', es: 'MARCH en ucraniano', pt: 'MARCH em ucraniano' },
              body: {
                en: 'Massive bleeding first: «кровотеча». Then airway and breathing: «дихає?». Ask the casualty questions — a man who answers is conscious («притомний»). A second casualty just came in; assess him and report in three words.',
                es: 'Primero la hemorragia masiva: «кровотеча». Luego vía aérea y respiración: «дихає?». Hazle preguntas al herido — quien responde está consciente («притомний»). Acaba de llegar un segundo herido; evalúalo e informa en tres palabras.',
                pt: 'Primeiro a hemorragia massiva: «кровотеча». Depois via aérea e respiração: «дихає?». Faça perguntas ao ferido — quem responde está consciente («притомний»). Um segundo ferido acabou de chegar; avalie e reporte em três palavras.',
              } },
            { type: 'line', lang: 'УК', uk: 'Ще один триста! Перевір його!', tr: 'shche odyn trysta! perevir yoho!', en: 'Another wounded man! Check him!', es: '¡Otro herido! ¡Revísalo!', pt: 'Mais um ferido! Verifique ele!' },
            { type: 'speak', uk: 'Ти мене чуєш? Де болить?', tr: 'ty mene chuiesh? de bolyt?', en: 'Can you hear me? Where does it hurt?', es: '¿Me oyes? ¿Dónde te duele?', pt: 'Você me ouve? Onde dói?' },
            { type: 'line', lang: 'УК', uk: 'Чую… Голова. Дуже болить.', tr: 'chuiu… holova. duzhe bolyt', en: 'I hear you… My head. It hurts a lot.', es: 'Te oigo… La cabeza. Duele mucho.', pt: 'Ouço… A cabeça. Dói muito.' },
            { type: 'speak', uk: 'Притомний. Дихає. Кровотечі немає.', tr: 'prytomnyi. dykhaie. krovotechi nemaie', en: 'Conscious. Breathing. No bleeding.', es: 'Consciente. Respira. Sin hemorragia.', pt: 'Consciente. Respira. Sem hemorragia.' },
            { type: 'line', lang: 'УК', uk: 'Контузія. Легкий. Веди його до стабпункту.', tr: 'kontuziia. lehkyi. vedy yoho do stabpunktu', en: 'Concussion. Walking wounded. Take him to the stab point.', es: 'Conmoción. Leve. Llévalo al punto de estabilización.', pt: 'Concussão. Leve. Leve ele ao ponto de estabilização.' },
            { type: 'choice',
              q: { en: 'What do you check first?', es: '¿Qué revisas primero?', pt: 'O que você verifica primeiro?' },
              options: [
                { label: 'пульс' },
                { label: 'кровотеча', right: true },
                { label: 'голова' },
              ] },
            { type: 'translate', uk: 'Кровотечі немає. Дихає.', tr: 'krovotechi nemaie. dykhaie',
              keywords: {
                en: [['no', 'not', "isn't"], ['bleeding', 'blood', 'haemorrhage', 'hemorrhage'], ['breathing', 'breathes', 'breath']],
                es: [['no', 'sin'], ['hemorragia', 'sangra', 'sangrado', 'sangre'], ['respira', 'respirando']],
                pt: [['não', 'sem'], ['hemorragia', 'sangra', 'sangramento', 'sangue'], ['respira', 'respirando']],
              },
              model: { en: 'No bleeding. He is breathing.', es: 'Sin hemorragia. Respira.', pt: 'Sem hemorragia. Está respirando.' } },
          ],
        },
        {
          id: 'evac',
          uk: 'Евакуація.', en: 'Evacuation.', es: 'Evacuación.', pt: 'Evacuação.',
          steps: [
            { type: 'info',
              title: { en: 'Calling it in', es: 'Avisar por radio', pt: 'Chamar pelo rádio' },
              body: {
                en: 'Over the radio, casualties are numbers: «триста» is wounded, «двісті» is dead. Say how many, how bad («важкий» critical / «легкий» light), and where. Then «прийом» — over.',
                es: 'Por radio, las bajas son números: «триста» es herido, «двісті» es muerto. Di cuántos, cómo de graves («важкий» grave / «легкий» leve) y dónde. Luego «прийом» — cambio.',
                pt: 'No rádio, baixas são números: «триста» é ferido, «двісті» é morto. Diga quantos, a gravidade («важкий» grave / «легкий» leve) e onde. Depois «прийом» — câmbio.',
              } },
            { type: 'line', lang: 'УК', uk: 'Доповідай! Скільки триста?', tr: 'dopovidai! skilky trysta?', en: 'Report! How many wounded?', es: '¡Informa! ¿Cuántos heridos?', pt: 'Reporte! Quantos feridos?' },
            { type: 'speak', uk: 'Два триста. Один важкий, один легкий.', tr: 'dva trysta. odyn vazhkyi, odyn lehkyi', en: 'Two wounded. One critical, one light.', es: 'Dos heridos. Uno grave, uno leve.', pt: 'Dois feridos. Um grave, um leve.' },
            { type: 'line', lang: 'УК', uk: 'Прийняв. Евак — через десять хвилин. Де ви?', tr: 'pryiniav. evak — cherez desiat khvylyn. de vy?', en: 'Copy. Evac in ten minutes. Where are you?', es: 'Recibido. Evacuación en diez minutos. ¿Dónde están?', pt: 'Entendido. Evacuação em dez minutos. Onde vocês estão?' },
            { type: 'speak', uk: 'Біля посадки, на дорозі. Прийом.', tr: 'bilia posadky, na dorozi. pryiom', en: 'By the tree line, on the road. Over.', es: 'Junto a la línea de árboles, en el camino. Cambio.', pt: 'Perto da linha de árvores, na estrada. Câmbio.' },
            { type: 'line', lang: 'УК', uk: 'Зрозумів. Ноші готуйте. Кінець зв’язку.', tr: 'zrozumiv. noshi hotuite. kinets zviazku', en: 'Understood. Get the stretcher ready. Out.', es: 'Entendido. Preparen la camilla. Corto.', pt: 'Entendido. Preparem a maca. Desligo.' },
            { type: 'choice',
              q: { en: 'Which word means “wounded” on the radio?', es: '¿Qué palabra significa «herido» por radio?', pt: 'Qual palavra significa «ferido» no rádio?' },
              options: [
                { label: 'двісті' },
                { label: 'триста', right: true },
                { label: 'сто' },
              ] },
          ],
        },
      ],
    },
    {
      id: 'first-class',
      track: '04',
      difficulty: 'B1',
      category: { en: 'INSTRUCTOR', es: 'INSTRUCTOR', pt: 'INSTRUTOR' },
      uk: 'Перше заняття.', en: 'First class.', es: 'Primera clase.', pt: 'Primeira aula.',
      keyTerms: ['наказ', 'Повторіть.', 'час', 'Готовий?'],
      scenes: [
        {
          id: 's1',
          uk: 'Перше заняття.', en: 'First class.', es: 'Primera clase.', pt: 'Primeira aula.',
          steps: [
            { type: 'line', lang: 'УК', uk: 'Слухай наказ. Повторюй за мною.', tr: 'slukhai nakaz. povtoriui za mnoiu', en: 'Listen to the order. Repeat after me.', es: 'Escucha la orden. Repite conmigo.', pt: 'Escute a ordem. Repita comigo.' },
            { type: 'speak', uk: 'Зрозумів. Повторіть, будь ласка.', tr: 'zrozumiv. povtorit, bud laska', en: 'Understood. Say again, please.', es: 'Entendido. Repita, por favor.', pt: 'Entendido. Repita, por favor.' },
            { type: 'line', lang: 'УК', uk: 'Повільно. Ще раз. Швидше!', tr: 'povilno. shche raz. shvydshe!', en: 'Slowly. Once more. Faster!', es: 'Despacio. Otra vez. ¡Más rápido!', pt: 'Devagar. Mais uma vez. Mais rápido!' },
            { type: 'line', lang: 'УК', uk: 'Добре. Час — п’ять хвилин. Готовий?', tr: 'dobre. chas — piat khvylyn. hotovyi?', en: 'Good. Five minutes. Ready?', es: 'Bien. Cinco minutos. ¿Listo?', pt: 'Bom. Cinco minutos. Pronto?' },
            { type: 'choice',
              q: { en: 'How do you ask someone to say it again?', es: '¿Cómo pides que lo repitan?', pt: 'Como você pede para repetirem?' },
              options: [
                { label: 'Повторіть.', right: true },
                { label: 'Швидше!' },
                { label: 'Тримай позицію!' },
              ] },
          ],
        },
        {
          id: 'interpreter',
          uk: 'Через перекладача.', en: 'Through an interpreter.', es: 'Con intérprete.', pt: 'Com intérprete.',
          steps: [
            { type: 'info',
              title: { en: 'Working with an interpreter', es: 'Trabajar con intérprete', pt: 'Trabalhar com intérprete' },
              body: {
                en: 'Speak to the soldiers, not to the interpreter. Short sentences, then pause. And learn the handful of words that bypass the interpreter entirely: «Дивись» (watch), «Повторюй за мною» (repeat after me), «Ще раз» (again), «Правильно» / «Неправильно», «Молодець».',
                es: 'Habla a los soldados, no al intérprete. Frases cortas, luego pausa. Y aprende las pocas palabras que no necesitan intérprete: «Дивись» (mira), «Повторюй за мною» (repite conmigo), «Ще раз» (otra vez), «Правильно» / «Неправильно», «Молодець».',
                pt: 'Fale com os soldados, não com o intérprete. Frases curtas, depois pausa. E aprenda as poucas palavras que dispensam o intérprete: «Дивись» (olhe), «Повторюй за мною» (repita comigo), «Ще раз» (de novo), «Правильно» / «Неправильно», «Молодець».',
              } },
            { type: 'speak', uk: 'Дивись. Повторюй за мною.', tr: 'dyvys. povtoriui za mnoiu', en: 'Watch. Repeat after me.', es: 'Mira. Repite conmigo.', pt: 'Olhe. Repita comigo.' },
            { type: 'line', lang: 'УК', uk: 'Так точно. Зрозумів.', tr: 'tak tochno. zrozumiv', en: 'Yes, sir. Understood.', es: 'Sí, señor. Entendido.', pt: 'Sim, senhor. Entendido.' },
            { type: 'speak', uk: 'Неправильно. Ще раз. Повільно.', tr: 'nepravylno. shche raz. povilno', en: 'Wrong. Once more. Slowly.', es: 'Incorrecto. Otra vez. Despacio.', pt: 'Errado. De novo. Devagar.' },
            { type: 'line', lang: 'УК', uk: 'Так? Правильно?', tr: 'tak? pravylno?', en: 'Like this? Correct?', es: '¿Así? ¿Correcto?', pt: 'Assim? Certo?' },
            { type: 'speak', uk: 'Правильно. Молодець!', tr: 'pravylno. molodets', en: 'Correct. Well done!', es: 'Correcto. ¡Bien hecho!', pt: 'Certo. Muito bem!' },
            { type: 'line', lang: 'УК', uk: 'Вони питають: скільки часу на вправу?', tr: 'vony pytaiut: skilky chasu na vpravu?', en: 'They ask: how much time for the exercise?', es: 'Preguntan: ¿cuánto tiempo para el ejercicio?', pt: 'Eles perguntam: quanto tempo para o exercício?' },
            { type: 'speak', uk: 'Десять хвилин. Потім — перерва.', tr: 'desiat khvylyn. potim — pererva', en: 'Ten minutes. Then a break.', es: 'Diez minutos. Luego, descanso.', pt: 'Dez minutos. Depois, intervalo.' },
            { type: 'choice',
              q: { en: 'How do you say “well done”?', es: '¿Cómo se dice «bien hecho»?', pt: 'Como se diz «muito bem»?' },
              options: [
                { label: 'Молодець!', right: true },
                { label: 'Неправильно.' },
                { label: 'Ще раз.' },
              ] },
          ],
        },
      ],
    },
    {
      id: 'przemysl-lviv',
      track: '05',
      difficulty: 'A1',
      category: { en: 'TRAVEL', es: 'VIAJE', pt: 'VIAGEM' },
      uk: 'Потяг до Львова.', en: 'The train to Lviv.', es: 'El tren a Lviv.', pt: 'O trem para Lviv.',
      keyTerms: ['паспорт', 'квиток', 'потяг', 'вагон', 'місце', 'кордон', 'вибачте', 'волонтер'],
      /* The ticket facts — train 35, carriage 7, seat 42, departure 17:20 —
         are set in scene 1's info card and quizzed again in scenes 1 and 4.
         Keep them in sync if you edit either. */
      scenes: [
        {
          id: 'border-pl',
          uk: 'Кордон у Перемишлі.', en: 'The border at Przemyśl.', es: 'La frontera en Przemyśl.', pt: 'A fronteira em Przemyśl.',
          steps: [
            { type: 'info',
              title: { en: 'Your ticket', es: 'Tu billete', pt: 'Seu bilhete' },
              body: {
                en: 'Train 35, Przemyśl → Lviv. Carriage 7, seat 42, departure 17:20. Before boarding, Polish officers check passports at the station — you mostly need «дякую» and «будь ласка». Memorise the ticket: you will be asked about it.',
                es: 'Tren 35, Przemyśl → Lviv. Vagón 7, asiento 42, salida 17:20. Antes de subir, los agentes polacos revisan pasaportes en la estación — sobre todo necesitas «дякую» y «будь ласка». Memoriza el billete: te preguntarán por él.',
                pt: 'Trem 35, Przemyśl → Lviv. Vagão 7, assento 42, partida 17:20. Antes de embarcar, os agentes poloneses conferem passaportes na estação — você precisa principalmente de «дякую» e «будь ласка». Memorize o bilhete: vão perguntar sobre ele.',
              } },
            { type: 'line', lang: 'УК', uk: 'Ваш паспорт, будь ласка.', tr: 'vash pasport, bud laska', en: 'Your passport, please.', es: 'Su pasaporte, por favor.', pt: 'Seu passaporte, por favor.' },
            { type: 'line', lang: 'EN', uk: 'Ось, будь ласка.', tr: 'os, bud laska', en: 'Here you are.', es: 'Aquí tiene.', pt: 'Aqui está.' },
            { type: 'speak', uk: 'Дякую.', tr: 'diakuiu', en: 'Thank you.', es: 'Gracias.', pt: 'Obrigado.' },
            { type: 'choice',
              q: { en: 'Which carriage is on your ticket?', es: '¿Qué vagón figura en tu billete?', pt: 'Qual vagão está no seu bilhete?' },
              options: [
                { label: '5' },
                { label: '7', right: true },
                { label: '9' },
              ] },
          ],
        },
        {
          id: 'platform',
          uk: 'Платформа і вагон.', en: 'Platform and carriage.', es: 'Plataforma y vagón.', pt: 'Plataforma e vagão.',
          steps: [
            { type: 'info',
              title: { en: 'Finding your seat', es: 'Encontrar tu asiento', pt: 'Encontrar seu assento' },
              body: {
                en: 'Platform 5, carriage 7, seat 42. People will answer with the direction words from the glossary: «прямо», «ліворуч», «праворуч». Ask — Ukrainians help.',
                es: 'Plataforma 5, vagón 7, asiento 42. Te responderán con las palabras de dirección del glosario: «прямо», «ліворуч», «праворуч». Pregunta — los ucranianos ayudan.',
                pt: 'Plataforma 5, vagão 7, assento 42. Vão responder com as palavras de direção do glossário: «прямо», «ліворуч», «праворуч». Pergunte — os ucranianos ajudam.',
              } },
            { type: 'line', lang: 'EN', uk: 'Вибачте, де п’ята платформа?', tr: 'vybachte, de piata platforma', en: 'Excuse me, where is platform five?', es: 'Disculpe, ¿dónde está la plataforma cinco?', pt: 'Desculpe, onde está a plataforma cinco?' },
            { type: 'line', lang: 'УК', uk: 'Прямо і ліворуч.', tr: 'priamo i livoruch', en: 'Straight ahead and to the left.', es: 'Todo recto y a la izquierda.', pt: 'Em frente e à esquerda.' },
            { type: 'speak', uk: 'Вибачте, де мій вагон?', tr: 'vybachte, de mii vahon', en: 'Excuse me, where is my carriage?', es: 'Disculpe, ¿dónde está mi vagón?', pt: 'Desculpe, onde está meu vagão?' },
            { type: 'line', lang: 'УК', uk: 'Сьомий вагон — там.', tr: 'somyi vahon — tam', en: 'Carriage seven is over there.', es: 'El vagón siete está allí.', pt: 'O vagão sete está ali.' },
            { type: 'line', lang: 'EN', uk: 'Це місце сорок два?', tr: 'tse mistse sorok dva', en: 'Is this seat forty-two?', es: '¿Es este el asiento cuarenta y dos?', pt: 'Este é o assento quarenta e dois?' },
            { type: 'line', lang: 'УК', uk: 'Так, сідайте, будь ласка.', tr: 'tak, sidaite, bud laska', en: 'Yes, take a seat, please.', es: 'Sí, siéntese, por favor.', pt: 'Sim, sente-se, por favor.' },
            { type: 'translate', uk: 'Прямо і ліворуч.', tr: 'priamo i livoruch',
              keywords: {
                en: [['straight', 'ahead', 'forward'], ['left']],
                es: [['recto', 'derecho', 'frente'], ['izquierda']],
                pt: [['frente', 'reto', 'direto'], ['esquerda']],
              },
              model: { en: 'Straight ahead and to the left.', es: 'Todo recto y a la izquierda.', pt: 'Em frente e à esquerda.' } },
          ],
        },
        {
          id: 'border-ua',
          uk: 'Прикордонний контроль.', en: 'Border control.', es: 'Control fronterizo.', pt: 'Controle de fronteira.',
          steps: [
            { type: 'info',
              title: { en: 'The questions to expect', es: 'Las preguntas que vienen', pt: 'As perguntas que vêm' },
              body: {
                en: 'On the train, Ukrainian border guards check documents. Expect three questions: purpose of visit, destination, and how long you are staying. Short, calm answers are perfect.',
                es: 'En el tren, los guardias fronterizos ucranianos revisan documentos. Espera tres preguntas: motivo del viaje, destino y cuánto tiempo te quedas. Respuestas cortas y tranquilas son perfectas.',
                pt: 'No trem, os guardas de fronteira ucranianos conferem documentos. Espere três perguntas: motivo da viagem, destino e por quanto tempo você fica. Respostas curtas e calmas são perfeitas.',
              } },
            { type: 'line', lang: 'УК', uk: 'Доброго дня. Прикордонний контроль. Паспорт, будь ласка.', tr: 'dobroho dnia. prykordonnyi kontrol. pasport, bud laska', en: 'Good day. Border control. Passport, please.', es: 'Buenos días. Control fronterizo. Pasaporte, por favor.', pt: 'Bom dia. Controle de fronteira. Passaporte, por favor.' },
            { type: 'line', lang: 'УК', uk: 'Мета візиту?', tr: 'meta vizytu', en: 'Purpose of visit?', es: '¿Motivo del viaje?', pt: 'Motivo da viagem?' },
            { type: 'speak', uk: 'Я волонтер. Їду до Львова.', tr: 'ya volonter. yidu do lvova', en: 'I am a volunteer. I am going to Lviv.', es: 'Soy voluntario. Voy a Lviv.', pt: 'Sou voluntário. Vou para Lviv.' },
            { type: 'line', lang: 'УК', uk: 'Як довго ви будете в Україні?', tr: 'yak dovho vy budete v ukraini', en: 'How long will you be in Ukraine?', es: '¿Cuánto tiempo estará en Ucrania?', pt: 'Quanto tempo você ficará na Ucrânia?' },
            { type: 'line', lang: 'EN', uk: 'Три місяці.', tr: 'try misiatsi', en: 'Three months.', es: 'Tres meses.', pt: 'Três meses.' },
            { type: 'line', lang: 'УК', uk: 'Дякую. Все добре. Гарної дороги!', tr: 'diakuiu. vse dobre. harnoi dorohy!', en: 'Thank you. All good. Have a good trip!', es: 'Gracias. Todo en orden. ¡Buen viaje!', pt: 'Obrigado. Tudo certo. Boa viagem!' },
            { type: 'choice',
              q: { en: 'How does the guard ask about the purpose of your visit?', es: '¿Cómo pregunta el guardia por el motivo de tu viaje?', pt: 'Como o guarda pergunta o motivo da sua viagem?' },
              options: [
                { label: 'Мета візиту?', right: true },
                { label: 'Як довго ви будете в Україні?' },
                { label: 'Ваші квитки, будь ласка.' },
              ] },
          ],
        },
        {
          id: 'conductor',
          uk: 'Провідник.', en: 'The conductor.', es: 'El revisor.', pt: 'O condutor.',
          steps: [
            { type: 'line', lang: 'УК', uk: 'Ваші квитки, будь ласка.', tr: 'vashi kvytky, bud laska', en: 'Your tickets, please.', es: 'Sus billetes, por favor.', pt: 'Suas passagens, por favor.' },
            { type: 'line', lang: 'EN', uk: 'Ось мій квиток.', tr: 'os mii kvytok', en: 'Here is my ticket.', es: 'Aquí está mi billete.', pt: 'Aqui está meu bilhete.' },
            { type: 'line', lang: 'УК', uk: 'Дякую. Чай, кава?', tr: 'diakuiu. chai, kava?', en: 'Thank you. Tea, coffee?', es: 'Gracias. ¿Té, café?', pt: 'Obrigado. Chá, café?' },
            { type: 'speak', uk: 'Чай, будь ласка. Дякую.', tr: 'chai, bud laska. diakuiu', en: 'Tea, please. Thank you.', es: 'Té, por favor. Gracias.', pt: 'Chá, por favor. Obrigado.' },
            { type: 'choice',
              q: { en: 'What time does train 35 depart?', es: '¿A qué hora sale el tren 35?', pt: 'A que horas parte o trem 35?' },
              options: [
                { label: '16:20' },
                { label: '17:20', right: true },
                { label: '18:40' },
              ] },
            { type: 'translate', uk: 'Ваші квитки, будь ласка.', tr: 'vashi kvytky, bud laska',
              keywords: {
                en: [['ticket', 'tickets'], ['please']],
                es: [['billete', 'billetes', 'boleto', 'boletos', 'pasaje', 'pasajes'], ['favor']],
                pt: [['bilhete', 'bilhetes', 'passagem', 'passagens'], ['favor']],
              },
              model: { en: 'Your tickets, please.', es: 'Sus billetes, por favor.', pt: 'Suas passagens, por favor.' } },
            { type: 'info',
              title: { en: 'Lviv', es: 'Lviv', pt: 'Lviv' },
              body: {
                en: 'Welcome to Lviv — Львів. You made it in, in Ukrainian. Next: Track 01, your first week in a unit.',
                es: 'Bienvenido a Lviv — Львів. Llegaste, y en ucraniano. Siguiente: la pista 01, tu primera semana en la unidad.',
                pt: 'Bem-vindo a Lviv — Львів. Você chegou, e em ucraniano. Próximo: a trilha 01, sua primeira semana na unidade.',
              } },
          ],
        },
      ],
    },
    {
      id: 'radio',
      track: '06',
      difficulty: 'A2',
      category: { en: 'RADIO', es: 'RADIO', pt: 'RÁDIO' },
      uk: 'На зв’язку.', en: 'On the radio.', es: 'En la radio.', pt: 'No rádio.',
      keyTerms: ['позивний', 'Як чуєш?', 'Чую добре.', 'прийняв', 'прийом', 'кінець зв’язку', 'Повтори.', 'триста'],
      /* The learner's call sign throughout is «Беркут»; the other station is
         «Сокіл» (sergeant Andrii from track 01). */
      scenes: [
        {
          id: 'check',
          uk: 'Перевірка зв’язку.', en: 'Radio check.', es: 'Comprobación de radio.', pt: 'Teste de rádio.',
          steps: [
            { type: 'info',
              title: { en: 'How a call works', es: 'Cómo funciona una llamada', pt: 'Como funciona uma chamada' },
              body: {
                en: 'Their call sign, then yours: «Сокіл, я Беркут». «Як чуєш?» is a radio check; the answer is «Чую добре» (or «Чую погано» — badly). End every transmission with «прийом» (over) and the whole exchange with «кінець зв’язку» (out). Your call sign in this course is Беркут — golden eagle.',
                es: 'Su indicativo, luego el tuyo: «Сокіл, я Беркут». «Як чуєш?» es una comprobación de radio; la respuesta es «Чую добре» (o «Чую погано» — mal). Termina cada transmisión con «прийом» (cambio) y toda la conversación con «кінець зв’язку» (corto). Tu indicativo en este curso es Беркут — águila real.',
                pt: 'O indicativo deles, depois o seu: «Сокіл, я Беркут». «Як чуєш?» é um teste de rádio; a resposta é «Чую добре» (ou «Чую погано» — mal). Termine cada transmissão com «прийом» (câmbio) e a conversa toda com «кінець зв’язку» (desligo). Seu indicativo neste curso é Беркут — águia-real.',
              } },
            { type: 'line', lang: 'УК', uk: 'Беркут, я Сокіл. Як чуєш? Прийом.', tr: 'berkut, ya sokil. yak chuiesh? pryiom', en: 'Berkut, this is Sokil. How do you read? Over.', es: 'Berkut, aquí Sokil. ¿Cómo me recibes? Cambio.', pt: 'Berkut, aqui Sokil. Como me recebe? Câmbio.' },
            { type: 'speak', uk: 'Сокіл, я Беркут. Чую добре. Прийом.', tr: 'sokil, ya berkut. chuiu dobre. pryiom', en: 'Sokil, this is Berkut. Reading you loud and clear. Over.', es: 'Sokil, aquí Berkut. Te recibo bien. Cambio.', pt: 'Sokil, aqui Berkut. Recebo bem. Câmbio.' },
            { type: 'line', lang: 'УК', uk: 'Прийняв. На зв’язку. Кінець зв’язку.', tr: 'pryiniav. na zviazku. kinets zviazku', en: 'Copy. Standing by. Out.', es: 'Recibido. A la escucha. Corto.', pt: 'Entendido. Na escuta. Desligo.' },
            { type: 'choice',
              q: { en: 'How do you end the whole exchange?', es: '¿Cómo terminas toda la conversación?', pt: 'Como você encerra a conversa toda?' },
              options: [
                { label: 'прийом' },
                { label: 'кінець зв’язку', right: true },
                { label: 'Як чуєш?' },
              ] },
            { type: 'translate', uk: 'Як чуєш? Прийом.', tr: 'yak chuiesh? pryiom',
              keywords: {
                en: [['read', 'hear', 'copy', 'receive'], ['over']],
                es: [['recibes', 'oyes', 'copias', 'escuchas'], ['cambio']],
                pt: [['recebe', 'ouve', 'copia', 'escuta'], ['câmbio', 'cambio']],
              },
              model: { en: 'How do you read me? Over.', es: '¿Cómo me recibes? Cambio.', pt: 'Como me recebe? Câmbio.' } },
          ],
        },
        {
          id: 'report',
          uk: 'Доповідь.', en: 'Report.', es: 'Informe.', pt: 'Relatório.',
          steps: [
            { type: 'info',
              title: { en: 'Reporting', es: 'Informar', pt: 'Reportar' },
              body: {
                en: 'Short and in order: who, where, what. «Я на позиції» (I am on position). «Противник на дванадцяту, п’ятсот метрів». If you did not catch it: «Повтори» — say again. Never guess a number you did not hear.',
                es: 'Corto y en orden: quién, dónde, qué. «Я на позиції» (estoy en posición). «Противник на дванадцяту, п’ятсот метрів». Si no lo captaste: «Повтори» — repite. Nunca adivines un número que no oíste.',
                pt: 'Curto e em ordem: quem, onde, o quê. «Я на позиції» (estou na posição). «Противник на дванадцяту, п’ятсот метрів». Se não captou: «Повтори» — repita. Nunca chute um número que não ouviu.',
              } },
            { type: 'line', lang: 'УК', uk: 'Беркут, я Сокіл. Доповідай. Прийом.', tr: 'berkut, ya sokil. dopovidai. pryiom', en: 'Berkut, this is Sokil. Report. Over.', es: 'Berkut, aquí Sokil. Informa. Cambio.', pt: 'Berkut, aqui Sokil. Reporte. Câmbio.' },
            { type: 'speak', uk: 'Сокіл, я Беркут. Я на позиції. Все добре. Прийом.', tr: 'sokil, ya berkut. ya na pozytsii. vse dobre. pryiom', en: 'Sokil, this is Berkut. I am on position. All good. Over.', es: 'Sokil, aquí Berkut. Estoy en posición. Todo bien. Cambio.', pt: 'Sokil, aqui Berkut. Estou na posição. Tudo bem. Câmbio.' },
            { type: 'line', lang: 'УК', uk: 'Прийняв. Противник — на дванадцяту, п’ятсот метрів. Тримай позицію. Прийом.', tr: 'pryiniav. protyvnyk — na dvanadtsiatu, piatsot metriv. trymai pozytsiiu. pryiom', en: 'Copy. Enemy at twelve o’clock, five hundred metres. Hold the position. Over.', es: 'Recibido. Enemigo a las doce, quinientos metros. Mantén la posición. Cambio.', pt: 'Entendido. Inimigo às doze horas, quinhentos metros. Mantenha a posição. Câmbio.' },
            { type: 'speak', uk: 'Повтори. Скільки метрів? Прийом.', tr: 'povtory. skilky metriv? pryiom', en: 'Say again. How many metres? Over.', es: 'Repite. ¿Cuántos metros? Cambio.', pt: 'Repita. Quantos metros? Câmbio.' },
            { type: 'line', lang: 'УК', uk: 'П’ятсот. П’ять — нуль — нуль. Прийом.', tr: 'piatsot. piat — nul — nul. pryiom', en: 'Five hundred. Five — zero — zero. Over.', es: 'Quinientos. Cinco — cero — cero. Cambio.', pt: 'Quinhentos. Cinco — zero — zero. Câmbio.' },
            { type: 'speak', uk: 'Прийняв. П’ятсот метрів. Тримаю позицію. Кінець зв’язку.', tr: 'pryiniav. piatsot metriv. trymaiu pozytsiiu. kinets zviazku', en: 'Copy. Five hundred metres. Holding position. Out.', es: 'Recibido. Quinientos metros. Mantengo la posición. Corto.', pt: 'Entendido. Quinhentos metros. Mantendo a posição. Desligo.' },
            { type: 'choice',
              q: { en: 'You did not catch the number. What do you say?', es: 'No captaste el número. ¿Qué dices?', pt: 'Você não captou o número. O que diz?' },
              options: [
                { label: 'Прийняв.' },
                { label: 'Повтори.', right: true },
                { label: 'Чую добре.' },
              ] },
          ],
        },
        {
          id: 'casualty',
          uk: 'Триста.', en: 'Three hundred.', es: 'Trescientos.', pt: 'Trezentos.',
          steps: [
            { type: 'line', lang: 'УК', uk: 'Беркут, я Сокіл. Що у вас? Прийом.', tr: 'berkut, ya sokil. shcho u vas? pryiom', en: 'Berkut, this is Sokil. What have you got? Over.', es: 'Berkut, aquí Sokil. ¿Qué tienen? Cambio.', pt: 'Berkut, aqui Sokil. O que vocês têm? Câmbio.' },
            { type: 'speak', uk: 'Сокіл, я Беркут. У нас триста. Один, важкий. Прийом.', tr: 'sokil, ya berkut. u nas trysta. odyn, vazhkyi. pryiom', en: 'Sokil, this is Berkut. We have a wounded man. One, critical. Over.', es: 'Sokil, aquí Berkut. Tenemos un herido. Uno, grave. Cambio.', pt: 'Sokil, aqui Berkut. Temos um ferido. Um, grave. Câmbio.' },
            { type: 'line', lang: 'УК', uk: 'Прийняв. Де ви? Прийом.', tr: 'pryiniav. de vy? pryiom', en: 'Copy. Where are you? Over.', es: 'Recibido. ¿Dónde están? Cambio.', pt: 'Entendido. Onde vocês estão? Câmbio.' },
            { type: 'speak', uk: 'Біля мосту, на дорозі. Потрібен евак. Прийом.', tr: 'bilia mostu, na dorozi. potriben evak. pryiom', en: 'By the bridge, on the road. We need evac. Over.', es: 'Junto al puente, en el camino. Necesitamos evacuación. Cambio.', pt: 'Perto da ponte, na estrada. Precisamos de evacuação. Câmbio.' },
            { type: 'line', lang: 'УК', uk: 'Зрозумів. Евак через десять хвилин. Тримайтеся. Кінець зв’язку.', tr: 'zrozumiv. evak cherez desiat khvylyn. trymaitesia. kinets zviazku', en: 'Understood. Evac in ten minutes. Hang in there. Out.', es: 'Entendido. Evacuación en diez minutos. Aguanten. Corto.', pt: 'Entendido. Evacuação em dez minutos. Aguentem. Desligo.' },
            { type: 'choice',
              q: { en: 'How do you say “we need evacuation”?', es: '¿Cómo se dice «necesitamos evacuación»?', pt: 'Como se diz «precisamos de evacuação»?' },
              options: [
                { label: 'Потрібен евак.', right: true },
                { label: 'Чую погано.' },
                { label: 'Тримай позицію!' },
              ] },
            { type: 'translate', uk: 'У нас триста. Один, важкий.', tr: 'u nas trysta. odyn, vazhkyi',
              keywords: {
                en: [['wounded', 'casualty', '300', 'injured'], ['one', '1', 'a '], ['critical', 'severe', 'serious', 'heavy', 'bad']],
                es: [['herido', 'baja', '300'], ['uno', 'un', '1'], ['grave', 'crítico', 'serio']],
                pt: [['ferido', 'baixa', '300'], ['um', '1'], ['grave', 'crítico', 'sério']],
              },
              model: { en: 'We have a wounded man. One, critical.', es: 'Tenemos un herido. Uno, grave.', pt: 'Temos um ferido. Um, grave.' } },
          ],
        },
      ],
    },
    {
      id: 'position',
      track: '07',
      difficulty: 'A1',
      category: { en: 'ON POSITION', es: 'EN POSICIÓN', pt: 'NA POSIÇÃO' },
      uk: 'На позиції.', en: 'On position.', es: 'En posición.', pt: 'Na posição.',
      keyTerms: ['окоп', 'бліндаж', 'посадка', 'Дрон!', 'В укриття!', 'Прикрий!', 'Відходимо!', 'Свої!'],
      scenes: [
        {
          id: 'moving-in',
          uk: 'Заходимо.', en: 'Moving in.', es: 'Entrando.', pt: 'Entrando.',
          steps: [
            { type: 'info',
              title: { en: 'Moving in', es: 'Entrar en posición', pt: 'Entrar na posição' },
              body: {
                en: 'You will move at night, in silence, behind someone who does not speak your language. Learn the words you will hear in a whisper: «за мною» (follow me), «стій» (stop), «тихо» (quiet), «окоп» (trench), «бліндаж» (dugout).',
                es: 'Te moverás de noche, en silencio, detrás de alguien que no habla tu idioma. Aprende las palabras que oirás en un susurro: «за мною» (sígueme), «стій» (alto), «тихо» (silencio), «окоп» (trinchera), «бліндаж» (refugio).',
                pt: 'Você vai se mover à noite, em silêncio, atrás de alguém que não fala sua língua. Aprenda as palavras que vai ouvir num sussurro: «за мною» (siga-me), «стій» (alto), «тихо» (silêncio), «окоп» (trincheira), «бліндаж» (abrigo).',
              } },
            { type: 'line', lang: 'УК', uk: 'Тихо. За мною. Не відставай.', tr: 'tykho. za mnoiu. ne vidstavai', en: 'Quiet. Follow me. Don’t fall behind.', es: 'Silencio. Sígueme. No te quedes atrás.', pt: 'Silêncio. Siga-me. Não fique para trás.' },
            { type: 'line', lang: 'УК', uk: 'Стій. Окоп — там, біля посадки. Бліндаж — ліворуч.', tr: 'stii. okop — tam, bilia posadky. blindazh — livoruch', en: 'Stop. The trench is there, by the tree line. The dugout is to the left.', es: 'Alto. La trinchera está allí, junto a la línea de árboles. El refugio, a la izquierda.', pt: 'Alto. A trincheira é ali, perto da linha de árvores. O abrigo, à esquerda.' },
            { type: 'speak', uk: 'Зрозумів. Окоп там, бліндаж ліворуч.', tr: 'zrozumiv. okop tam, blindazh livoruch', en: 'Understood. Trench there, dugout to the left.', es: 'Entendido. Trinchera allí, refugio a la izquierda.', pt: 'Entendido. Trincheira ali, abrigo à esquerda.' },
            { type: 'line', lang: 'УК', uk: 'Твоя позиція — тут. Тримай позицію до ранку.', tr: 'tvoia pozytsiia — tut. trymai pozytsiiu do ranku', en: 'Your position is here. Hold it until morning.', es: 'Tu posición es aquí. Mantenla hasta la mañana.', pt: 'Sua posição é aqui. Mantenha até de manhã.' },
            { type: 'speak', uk: 'Так точно. Тримаю позицію.', tr: 'tak tochno. trymaiu pozytsiiu', en: 'Yes, sir. Holding position.', es: 'Sí, señor. Mantengo la posición.', pt: 'Sim, senhor. Mantendo a posição.' },
            { type: 'choice',
              q: { en: 'Where is the dugout?', es: '¿Dónde está el refugio?', pt: 'Onde é o abrigo?' },
              options: [
                { label: 'ліворуч', right: true },
                { label: 'праворуч' },
                { label: 'прямо' },
              ] },
          ],
        },
        {
          id: 'drone',
          uk: 'Дрон!', en: 'Drone!', es: '¡Dron!', pt: 'Drone!',
          steps: [
            { type: 'info',
              title: { en: 'Drones', es: 'Drones', pt: 'Drones' },
              body: {
                en: 'The single most important word on the line. When you hear «Дрон!», «Птах!» or «Повітря!» — get into cover, do not look up, do not run in the open. When you see one first, you shout it — in Ukrainian, so everyone reacts.',
                es: 'La palabra más importante en la línea. Cuando oigas «Дрон!», «Птах!» o «Повітря!» — a cubierto, no mires arriba, no corras a campo abierto. Si lo ves tú primero, grítalo — en ucraniano, para que todos reaccionen.',
                pt: 'A palavra mais importante na linha. Quando ouvir «Дрон!», «Птах!» ou «Повітря!» — vá para o abrigo, não olhe para cima, não corra no aberto. Se você vir primeiro, grite — em ucraniano, para que todos reajam.',
              } },
            { type: 'line', lang: 'УК', uk: 'Дрон! В укриття!', tr: 'dron! v ukryttia!', en: 'Drone! Take cover!', es: '¡Dron! ¡A cubierto!', pt: 'Drone! Abriguem-se!' },
            { type: 'speak', uk: 'Дрон! В укриття!', tr: 'dron! v ukryttia', en: 'Drone! Take cover!', es: '¡Dron! ¡A cubierto!', pt: 'Drone! Abriguem-se!' },
            { type: 'line', lang: 'УК', uk: 'Тихо. Не рухайся. Чекай.', tr: 'tykho. ne rukhaisia. chekai', en: 'Quiet. Don’t move. Wait.', es: 'Silencio. No te muevas. Espera.', pt: 'Silêncio. Não se mexa. Espere.' },
            { type: 'line', lang: 'УК', uk: 'Відбій. Пішов. Все добре?', tr: 'vidbii. pishov. vse dobre?', en: 'All clear. It’s gone. Everyone OK?', es: 'Despejado. Se fue. ¿Todo bien?', pt: 'Tudo limpo. Foi embora. Tudo bem?' },
            { type: 'speak', uk: 'Все добре. Всі цілі.', tr: 'vse dobre. vsi tsili', en: 'All good. Everyone’s unhurt.', es: 'Todo bien. Todos ilesos.', pt: 'Tudo bem. Todos ilesos.' },
            { type: 'choice',
              q: { en: 'You hear «Птах!». What is it?', es: 'Oyes «Птах!». ¿Qué es?', pt: 'Você ouve «Птах!». O que é?' },
              options: [
                { label: 'Міни!' },
                { label: 'Дрон!', right: true },
                { label: 'Свої!' },
              ] },
            { type: 'translate', uk: 'Не рухайся. Чекай.', tr: 'ne rukhaisia. chekai',
              keywords: {
                en: [['move', 'still', 'moving'], ['wait']],
                es: [['muevas', 'quieto', 'mueves', 'moverse'], ['espera', 'espere']],
                pt: [['mexa', 'mova', 'parado', 'quieto', 'mexe'], ['espere', 'espera', 'aguarde']],
              },
              model: { en: 'Don’t move. Wait.', es: 'No te muevas. Espera.', pt: 'Não se mexa. Espere.' } },
          ],
        },
        {
          id: 'pull-back',
          uk: 'Відхід.', en: 'Pulling back.', es: 'Retirada.', pt: 'Recuo.',
          steps: [
            { type: 'info',
              title: { en: 'Pulling back', es: 'Retirarse', pt: 'Recuar' },
              body: {
                en: 'A withdrawal is where foreigners get lost. «Відходимо!» — we are pulling back. «Прикрий!» — cover me; «Прикриваю!» — covering. And when your own troops come towards you in the dark, shout «Свої!» so nobody shoots.',
                es: 'La retirada es donde se pierden los extranjeros. «Відходимо!» — nos retiramos. «Прикрий!» — cúbreme; «Прикриваю!» — cubriendo. Y cuando los tuyos vengan hacia ti en la oscuridad, grita «Свої!» para que nadie dispare.',
                pt: 'O recuo é onde os estrangeiros se perdem. «Відходимо!» — estamos recuando. «Прикрий!» — me cubra; «Прикриваю!» — cobrindo. E quando os seus vierem na sua direção no escuro, grite «Свої!» para ninguém atirar.',
              } },
            { type: 'line', lang: 'УК', uk: 'Контакт! На третю! Прикрий!', tr: 'kontakt! na tretiu! prykryi!', en: 'Contact! Three o’clock! Cover me!', es: '¡Contacto! ¡A las tres! ¡Cúbreme!', pt: 'Contato! Às três horas! Me cubra!' },
            { type: 'speak', uk: 'Прикриваю!', tr: 'prykryvaiu', en: 'Covering!', es: '¡Cubriendo!', pt: 'Cobrindo!' },
            { type: 'line', lang: 'УК', uk: 'Відходимо! До бліндажа! Бігом!', tr: 'vidkhodymo! do blindazha! bihom!', en: 'We’re pulling back! To the dugout! Run!', es: '¡Nos retiramos! ¡Al refugio! ¡Corriendo!', pt: 'Estamos recuando! Para o abrigo! Correndo!' },
            { type: 'speak', uk: 'Свої! Не стріляти! Свої!', tr: 'svoi! ne striliaty! svoi!', en: 'Friendlies! Don’t shoot! Friendlies!', es: '¡Son nuestros! ¡No disparen! ¡Nuestros!', pt: 'São nossos! Não atirem! Nossos!' },
            { type: 'line', lang: 'УК', uk: 'Всі тут? Поранені є?', tr: 'vsi tut? poraneni ye?', en: 'Everyone here? Any wounded?', es: '¿Están todos? ¿Hay heridos?', pt: 'Todos aqui? Tem feridos?' },
            { type: 'speak', uk: 'Всі тут. Поранених немає.', tr: 'vsi tut. poranenykh nemaie', en: 'Everyone’s here. No wounded.', es: 'Todos aquí. No hay heridos.', pt: 'Todos aqui. Sem feridos.' },
            { type: 'choice',
              q: { en: 'Your own troops are coming towards you at night. You shout:', es: 'Los tuyos vienen hacia ti de noche. Gritas:', pt: 'Os seus vêm na sua direção à noite. Você grita:' },
              options: [
                { label: 'Вогонь!' },
                { label: 'Свої!', right: true },
                { label: 'Контакт!' },
              ] },
          ],
        },
      ],
    },
  ];

  window.PK = { SECTIONS, TERMS, TRACKS, SCENARIOS };
})();
